export interface Guide {
  id: number;
  slug: string;
  title: string;
  titleTr: string;
  excerpt: string;
  excerptTr: string;
  bodyEn: string[];
  bodyTr: string[];
  keyPoints?: string[];
  keyPointsTr?: string[];
  category: string;
  categoryTr: string;
  ctaType: 'soft' | 'hard' | 'inline';
  ctaText: string;
  ctaTextTr: string;
  ctaLink?: string;
  image: string;
}

export const knowledgeCategories = [
  { en: 'All', tr: 'Tümü' },
  { en: 'London Real Estate', tr: 'Londra Gayrimenkul' },
  { en: 'Dubai Real Estate', tr: 'Dubai Gayrimenkul' },
  { en: 'Residency by Investment', tr: 'Yatırım ile Oturum' },
  { en: 'Business Expansion', tr: 'İş Geliştirme' },
];

export const guides: Guide[] = [
  {
    id: 1,
    slug: 'what-is-stamp-duty',
    title: 'What is Stamp Duty in the UK?',
    titleTr: 'İngiltere\'de Damga Vergisi (Stamp Duty) Nedir?',
    excerpt: 'Stamp Duty is a tax paid when purchasing property in the UK. The amount depends on the property value and buyer status.',
    excerptTr: 'Damga Vergisi, İngiltere\'de gayrimenkul satın alırken ödenen bir vergidir. Tutar, mülk değerine ve alıcının statüsüne bağlıdır.',
    bodyEn: [
      'Stamp Duty Land Tax (SDLT) is a government tax payable when you buy residential property or land over a certain price in England and Northern Ireland. As one of the most significant transaction costs for property investors, understanding how SDLT works is essential before committing to any UK property purchase.',
      'The tax is calculated on a tiered basis. For residential properties, the first £250,000 is tax-free for standard purchases. The next band from £250,001 to £925,000 attracts a 5% rate, while the portion between £925,001 and £1,500,000 is taxed at 10%. Any amount above £1,500,000 incurs a 12% charge.',
      'For overseas buyers, an additional 2% surcharge applies on top of the standard rates across all bands. This means a non-UK resident purchasing a £500,000 property would pay approximately £22,500 in SDLT, compared to £12,500 for a UK resident making the same purchase.',
      'Higher rates also apply if you already own a residential property. The 3% additional rate for second homes and buy-to-let investments is applied across all bands, creating a meaningful consideration for portfolio investors building a multi-property portfolio in the UK.',
    ],
    bodyTr: [
      'Damga Vergisi Arazi Vergisi (SDLT), İngiltere ve Kuzey İrlanda\'da belirli bir fiyatın üzerinde konut mülkü veya arazi satın aldığınızda ödenen bir devlet vergisidir. Gayrimenkul yatırımcıları için en önemli işlem maliyetlerinden biri olan SDLT\'nin nasıl çalıştığını anlamak, herhangi bir İngiltere mülk alımına karar vermeden önce büyük önem taşır.',
      'Vergi kademeli olarak hesaplanır. Konut mülkleri için standart alımlarda ilk 250.000 £ vergiden muaftır. 250.001–925.000 £ aralığı %5, 925.001–1.500.000 £ aralığı %10, 1.500.000 £ üstü ise %12 oranında vergilendirilir.',
      'Yurt dışından gelen alıcılar için tüm kademelerde standart oranların üzerine ek %2 eklenir. Bu durum, 500.000 £\'luk bir mülk satın alan İngiltere dışı mukimin yaklaşık 22.500 £ SDLT ödemesi; aynı alımı yapan bir İngiltere mukiminin ise 12.500 £ ödemesi anlamına gelir.',
      'Halihazırda bir konut mülkünüze sahipseniz daha yüksek oranlar da geçerlidir. İkinci konutlar ve kiralık yatırımlar için uygulanan ek %3 oranı tüm kademelerde uygulanarak, İngiltere\'de çoklu mülk portföyü oluşturan yatırımcılar için dikkate alınması gereken önemli bir faktör oluşturur.',
    ],
    category: 'London Real Estate',
    categoryTr: 'Londra Gayrimenkul',
    ctaType: 'soft',
    ctaText: 'Calculate your stamp duty',
    ctaTextTr: 'Damga verginizi hesaplayın',
    ctaLink: 'https://www.gov.uk/stamp-duty-land-tax/residential-property-rates',
    image: '/guides/sasun-bughdaryan-MswXuFp9DzY-unsplash.jpg',
  },
  {
    id: 2,
    slug: 'uk-mortgage-overseas-investors',
    title: 'How Does Mortgage Work in London for Overseas Investors?',
    titleTr: 'Yurt Dışından Yatırımcılar İçin Londra\'da Mortgage Nasıl Çalışır?',
    excerpt: 'Overseas investors can access mortgage financing in the UK, typically requiring a deposit between 25–40%.',
    excerptTr: 'Yurt dışından yatırımcılar, genellikle %25–40 arasında peşinat gerektiren İngiltere\'de mortgage finansmanına erişebilir.',
    bodyEn: [
      'Securing a mortgage as an overseas investor in the UK is entirely possible, though the process involves specific requirements that differ from domestic buyers. Understanding these nuances early in your investment journey can help you structure the purchase effectively and secure the most competitive terms available.',
      'Most international buyers will need to provide a deposit of between 25% and 40% of the property value. The exact percentage depends on several factors including the lender, your country of residence, income verification methods and the property type. Buy-to-let mortgages for overseas investors typically require higher deposits than residential mortgages.',
      'Lender options for international applicants have expanded in recent years, though the field remains more limited than for UK residents. Specialist international banks, private banks and select UK high-street lenders offer products tailored to overseas buyers. Interest rates typically sit 0.5% to 1.5% above equivalent UK resident rates.',
      'Income verification is a critical step. Lenders will assess your global income and may require translated and certified financial documents. Rental income from the target property can sometimes be factored into affordability calculations, particularly for buy-to-let applications where projected rental yields meet minimum coverage ratios.',
    ],
    bodyTr: [
      'İngiltere\'de yurt dışından yatırımcı olarak mortgage almak tamamen mümkündür; ancak süreç, yerel alıcılardan farklı belirli gereksinimler içerir. Bu nüansları yatırım yolculuğunuzun erken aşamalarında anlamak, satın almayı etkili bir şekilde yapılandırmanıza ve mevcut en rekabetçi koşulları elde etmenize yardımcı olabilir.',
      'Çoğu uluslararası alıcının mülk değerinin %25 ile %40 arasında bir peşinat sağlaması gerekecektir. Kesin yüzde; kredi veren kuruluş, ikamet ettiğiniz ülke, gelir doğrulama yöntemleri ve mülk türü dahil olmak üzere çeşitli faktörlere bağlıdır.',
      'Uluslararası başvuru sahipleri için kredi veren seçenekleri son yıllarda genişlemiş olsa da alan İngiltere mukimlerine kıyasla daha sınırlı kalmaktadır. Uzman uluslararası bankalar, özel bankalar ve seçili İngiltere perakende bankaları, yurt dışından alıcılara yönelik ürünler sunmaktadır.',
      'Gelir doğrulama kritik bir adımdır. Kredi verenler küresel gelirinizi değerlendirecek ve tercüme edilmiş, onaylı finansal belgeler talep edebilecektir. Hedef mülkten elde edilecek kira geliri, özellikle kiralık yatırım başvurularında öngörülen kira getirilerinin minimum karşılama oranlarını karşıladığı durumlarda, borç ödeme kapasitesi hesaplamalarına dahil edilebilir.',
    ],
    keyPoints: [
      'Limited lender options compared to UK residents',
      'Interest rates may vary — typically 0.5–1.5% higher',
      'Rental income can be considered for buy-to-let',
      'Deposit requirement: 25–40% for overseas buyers',
    ],
    keyPointsTr: [
      'İngiltere mukimlerine kıyasla sınırlı kredi veren seçenekleri',
      'Faiz oranları değişkenlik gösterebilir — genellikle %0,5–1,5 daha yüksek',
      'Kiralık yatırımlar için kira geliri dikkate alınabilir',
      'Peşinat gereksinimi: Yurt dışı alıcılar için %25–40',
    ],
    category: 'London Real Estate',
    categoryTr: 'Londra Gayrimenkul',
    ctaType: 'hard',
    ctaText: 'Speak with an advisor about financing options',
    ctaTextTr: 'Finansman seçenekleri hakkında danışmanla görüşün',
    image: '/guides/jakub-zerdzicki-QgXJUf6-cv8-unsplash.jpg',
  },
  {
    id: 3,
    slug: 'best-areas-rental-yield-london',
    title: 'Best Areas for Rental Yield in London',
    titleTr: 'Londra\'da En Yüksek Kira Getirisi Sunan Bölgeler',
    excerpt: 'Discover which London boroughs offer the strongest rental yields for property investors in 2026.',
    excerptTr: '2026 yılında gayrimenkul yatırımcıları için en güçlü kira getirisi sunan Londra ilçelerini keşfedin.',
    bodyEn: [
      'Rental yield is one of the most important metrics for property investors, representing the annual rental income as a percentage of the property\'s purchase price. In London, yields vary significantly between boroughs, property types and proximity to transport links, making location selection a critical investment decision.',
      'East London boroughs including Barking & Dagenham, Newham and Waltham Forest currently lead Greater London with gross yields between 5.2% and 6.8%. The Elizabeth Line and ongoing regeneration in Stratford and the Royal Docks continue to attract tenant demand while property prices remain comparatively accessible.',
      'South London offers strong potential in areas such as Woolwich, Lewisham and Croydon, where yields range from 4.8% to 5.9%. Woolwich Arsenal, with the completion of new developments and its direct transport links to Canary Wharf, represents a compelling opportunity for investors seeking above-average income returns.',
      'Prime Central London — areas like Mayfair, Knightsbridge and Chelsea — typically delivers lower yields of 2.5–3.5%, but compensates with stronger long-term capital growth and lower vacancy rates. The optimal strategy depends on your investment horizon: yield-focused investors may prefer outer zones, while those prioritising capital appreciation and wealth preservation may favour prime locations.',
    ],
    bodyTr: [
      'Kira getirisi, gayrimenkul yatırımcıları için en önemli göstergelerden biridir ve yıllık kira gelirini mülkün satın alma fiyatının yüzdesi olarak temsil eder. Londra\'da getiriler ilçeler, mülk türleri ve ulaşım bağlantılarına yakınlığa göre önemli ölçüde değişmektedir.',
      'Barking & Dagenham, Newham ve Waltham Forest dahil Doğu Londra ilçeleri, %5,2 ile %6,8 arasında brüt getirilerle şu anda Büyük Londra\'ya liderlik etmektedir. Elizabeth Hattı ve Stratford ile Royal Docks\'taki devam eden kentsel dönüşüm, kiracı talebini çekmeye devam etmektedir.',
      'Güney Londra, Woolwich, Lewisham ve Croydon gibi bölgelerde %4,8 ile %5,9 arasında getirilerle güçlü bir potansiyel sunmaktadır. Woolwich Arsenal, yeni gelişmelerin tamamlanması ve Canary Wharf\'a doğrudan ulaşım bağlantılarıyla ortalamanın üzerinde gelir getirisi arayan yatırımcılar için cazip bir fırsat sunmaktadır.',
      'Prime Central Londra — Mayfair, Knightsbridge ve Chelsea gibi bölgeler — genellikle %2,5–3,5 gibi daha düşük getiriler sunar ancak daha güçlü uzun vadeli sermaye büyümesi ve düşük boşluk oranlarıyla telafi eder. En uygun strateji yatırım ufkunuza bağlıdır.',
    ],
    category: 'London Real Estate',
    categoryTr: 'Londra Gayrimenkul',
    ctaType: 'inline',
    ctaText: 'Want a personalised investment breakdown?',
    ctaTextTr: 'Kişiselleştirilmiş bir yatırım analizi ister misiniz?',
    image: '/guides/photo-1460925895917-afdab827c52f.jpeg',
  },
  {
    id: 4,
    slug: 'buying-process-overseas-investors-uk',
    title: 'Buying Process for Overseas Investors in the UK',
    titleTr: 'Yurt Dışından Yatırımcılar İçin İngiltere\'de Satın Alma Süreci',
    excerpt: 'A step-by-step guide to purchasing property in the UK as an international investor.',
    excerptTr: 'Uluslararası bir yatırımcı olarak İngiltere\'de mülk satın alma sürecinin adım adım rehberi.',
    bodyEn: [
      'Purchasing property in the UK as an overseas investor follows a well-established legal process, though it differs meaningfully from many other jurisdictions. There are no restrictions on foreign ownership of UK property, making the country one of the most open real estate markets globally for international capital.',
      'The process typically begins with property selection and a reservation, followed by instructing a UK solicitor to handle the legal conveyancing. Your solicitor will conduct property searches, review the title and negotiate contract terms on your behalf. This stage usually takes 8–12 weeks for a standard transaction.',
      'Exchange of contracts is the pivotal moment when both buyer and seller become legally bound. At this point, you will typically pay a 10% deposit. Completion — the transfer of ownership and remaining funds — follows exchange, often within 2–4 weeks. For new-build properties, exchange may happen well before the building is completed.',
      'Key considerations for overseas buyers include setting up a UK bank account (not always required but practical), appointing a tax advisor familiar with non-resident taxation, and planning for ongoing management if the property is to be let. An experienced property advisory team can coordinate all service providers and ensure the process runs smoothly from initial enquiry through to tenancy.',
    ],
    bodyTr: [
      'İngiltere\'de yurt dışından yatırımcı olarak mülk satın alma işlemi, köklü bir hukuki süreci takip eder. İngiltere mülkünün yabancılar tarafından sahiplenilmesi konusunda herhangi bir kısıtlama bulunmamakta olup bu durum ülkeyi uluslararası sermaye için en açık gayrimenkul piyasalarından biri yapmaktadır.',
      'Süreç genellikle mülk seçimi ve rezervasyonla başlar, ardından hukuki devir işlemlerini yönetecek bir İngiltere avukatının görevlendirilmesiyle devam eder. Avukatınız mülk araştırmaları yapacak, tapuyu inceleyecek ve sizin adınıza sözleşme şartlarını müzakere edecektir.',
      'Sözleşme değişimi, alıcı ile satıcının hukuken bağlandığı kritik andır. Bu noktada genellikle %10 peşinat ödersiniz. Tamamlama — mülkiyetin ve kalan fonların devri — genellikle 2-4 hafta içinde gerçekleşir.',
      'Yurt dışından alıcılar için önemli hususlar arasında İngiltere banka hesabı açmak, mukim olmayanlara yönelik vergilendirme konusunda deneyimli bir vergi danışmanı atamak ve mülk kiraya verilecekse devam eden yönetim planlaması yer almaktadır.',
    ],
    category: 'London Real Estate',
    categoryTr: 'Londra Gayrimenkul',
    ctaType: 'hard',
    ctaText: 'Get a full investment breakdown',
    ctaTextTr: 'Kapsamlı bir yatırım analizi alın',
    image: '/guides/scott-graham-5fNmWej4tAA-unsplash.jpg',
  },
  {
    id: 5,
    slug: 'freehold-vs-leasehold-dubai',
    title: 'Freehold vs Leasehold in Dubai: What Investors Need to Know',
    titleTr: 'Dubai\'de Freehold ve Leasehold: Yatırımcıların Bilmesi Gerekenler',
    excerpt: 'Understanding the difference between freehold and leasehold ownership is essential before investing in Dubai real estate.',
    excerptTr: 'Dubai gayrimenkulüne yatırım yapmadan önce freehold ve leasehold mülkiyet arasındaki farkı anlamak büyük önem taşır.',
    bodyEn: [
      'Dubai\'s property market offers two primary ownership structures: freehold and leasehold. Since 2002, the UAE government has permitted foreign nationals to purchase freehold property in designated areas, opening the market to international investment on a large scale.',
      'Freehold ownership grants the buyer complete ownership of both the property and the land it sits on, in perpetuity. Popular freehold zones include Dubai Marina, Downtown Dubai, Palm Jumeirah, Business Bay and Jumeirah Beach Residence. This is the preferred structure for most international investors as it provides the strongest ownership rights and is the most straightforward for resale.',
      'Leasehold ownership, by contrast, grants the right to use the property for a fixed term — typically 30 to 99 years — after which ownership reverts to the freeholder. Lease terms in Dubai are generally very long and renewable, but the structure is more common in older developments and certain non-designated areas.',
      'For investment purposes, freehold properties typically command higher resale values and are easier to finance through local banks. They also qualify for long-term residency visas under recent UAE legislation, adding an important lifestyle benefit for investors who wish to spend time in Dubai. Our advisory team recommends freehold acquisition in established communities for the strongest combination of capital protection and rental yield.',
    ],
    bodyTr: [
      'Dubai gayrimenkul piyasası iki temel mülkiyet yapısı sunar: freehold ve leasehold. 2002 yılından bu yana BAE hükümeti, yabancı uyrukluların belirlenmiş bölgelerde freehold mülk satın almasına izin vererek piyasayı uluslararası yatırıma büyük ölçüde açmıştır.',
      'Freehold mülkiyet, alıcıya hem mülk hem de üzerinde bulunduğu arazi üzerinde süresiz tam mülkiyet hakkı tanır. Popüler freehold bölgeler arasında Dubai Marina, Downtown Dubai, Palm Jumeirah, Business Bay ve Jumeirah Beach Residence yer almaktadır.',
      'Leasehold mülkiyet ise mülkü belirli bir süre — genellikle 30 ila 99 yıl — kullanma hakkı tanır ve süre sonunda mülkiyet freehold sahibine geri döner. Dubai\'daki kiralama süreleri genellikle çok uzun ve yenilenebilirdir.',
      'Yatırım amacıyla, freehold mülkler genellikle daha yüksek yeniden satış değerlerine sahiptir ve yerel bankalar aracılığıyla finanse edilmesi daha kolaydır. Ayrıca son BAE mevzuatı kapsamında uzun süreli oturma izni vizelerine de hak kazandırırlar.',
    ],
    category: 'Dubai Real Estate',
    categoryTr: 'Dubai Gayrimenkul',
    ctaType: 'soft',
    ctaText: 'Explore Dubai freehold properties',
    ctaTextTr: 'Dubai freehold mülklerini keşfedin',
    image: '/guides/photo-1600585154340-be6161a56a0c.jpeg',
  },
  {
    id: 6,
    slug: 'roi-dubai-property',
    title: 'Understanding ROI in Dubai Real Estate',
    titleTr: 'Dubai Gayrimenkulünde YGO (Yatırım Getiri Oranı)',
    excerpt: 'Dubai consistently offers some of the highest rental yields among global cities, with returns ranging from 5% to 9%.',
    excerptTr: 'Dubai, küresel şehirler arasında %5 ile %9 arasında değişen getirilerle en yüksek kira verimlerinden bazılarını sunmaktadır.',
    bodyEn: [
      'Return on Investment (ROI) in Dubai real estate has consistently outperformed many major global markets, making the emirate a compelling destination for yield-focused investors. The combination of zero income tax, strong tenant demand and competitive property prices creates an attractive investment equation.',
      'Gross rental yields in Dubai currently range from 5% to 9% depending on location, property type and unit size. Studio and one-bedroom apartments in high-demand areas such as Dubai Marina, JVC (Jumeirah Village Circle) and Business Bay tend to deliver the highest percentage yields, while larger units in premium locations offer lower yields but stronger capital appreciation.',
      'Net yields — after accounting for service charges, maintenance and management fees — typically sit 1.5% to 2.5% below gross yields. Annual service charges in Dubai range from AED 12 to AED 30 per square foot depending on the community and the level of amenities provided. Understanding these ongoing costs is essential for accurate return projections.',
      'Capital appreciation adds another dimension to total returns. Dubai property prices have shown cyclical patterns, with prime areas demonstrating 8–15% annual appreciation during growth phases. Timing entry and exit points, diversifying across communities and choosing developments from reputable builders are key strategies for maximising total investment returns.',
    ],
    bodyTr: [
      'Dubai gayrimenkulünde yatırım getirisi (ROI), birçok büyük küresel piyasayı sürekli olarak geride bırakmıştır. Sıfır gelir vergisi, güçlü kiracı talebi ve rekabetçi mülk fiyatlarının kombinasyonu, cazip bir yatırım denklemi oluşturmaktadır.',
      'Dubai\'daki brüt kira getirileri, konum, mülk türü ve birim büyüklüğüne bağlı olarak şu anda %5 ile %9 arasında değişmektedir. Dubai Marina, JVC ve Business Bay gibi yüksek talep gören bölgelerdeki stüdyo ve tek yatak odalı daireler en yüksek yüzdelik getirileri sunma eğilimindedir.',
      'Net getiriler — hizmet bedelleri, bakım ve yönetim ücretleri düşüldükten sonra — genellikle brüt getirilerin %1,5 ile %2,5 altında yer almaktadır. Dubai\'daki yıllık hizmet bedelleri, topluluğa ve sağlanan olanaklara bağlı olarak metrekare başına 12-30 AED arasında değişmektedir.',
      'Sermaye değer artışı, toplam getirilere başka bir boyut ekler. Dubai mülk fiyatları döngüsel kalıplar sergilemiştir; prime bölgeler büyüme aşamalarında yıllık %8-15 değer artışı göstermektedir.',
    ],
    category: 'Dubai Real Estate',
    categoryTr: 'Dubai Gayrimenkul',
    ctaType: 'hard',
    ctaText: 'Get investment plan',
    ctaTextTr: 'Yatırım planı alın',
    image: '/guides/omid-armin-8Nppe0yLmn8-unsplash.jpg',
  },
  {
    id: 7,
    slug: 'buying-process-dubai',
    title: 'Buying Process in Dubai for International Investors',
    titleTr: 'Uluslararası Yatırımcılar İçin Dubai\'de Satın Alma Süreci',
    excerpt: 'A comprehensive guide to the Dubai property purchase process from reservation to title deed registration.',
    excerptTr: 'Rezervasyondan tapu tesciline kadar Dubai mülk satın alma sürecinin kapsamlı rehberi.',
    bodyEn: [
      'Buying property in Dubai as a foreign investor is a remarkably streamlined process compared to many international markets. The Dubai Land Department (DLD) oversees all transactions and maintains a transparent, digitised system that has significantly reduced bureaucratic delays.',
      'The process begins with property selection and a reservation, typically secured with a 5–10% deposit paid directly to the developer or seller\'s escrow account. For off-plan purchases, a Sale and Purchase Agreement (SPA) is signed with a payment plan structured according to construction milestones.',
      'For completed (ready) properties, the transaction proceeds through a No Objection Certificate (NOC) from the developer — confirming no outstanding service charges — followed by the transfer of title at the Dubai Land Department. The DLD charges a 4% transfer fee, split equally between buyer and seller by default, though this is often negotiated.',
      'Total transaction timeline for a ready property is typically 2–4 weeks from agreement to title deed transfer. Off-plan purchases follow the developer\'s construction timeline. International buyers do not require a UAE residency visa to purchase, though properties valued at AED 750,000 or above may qualify the owner for a renewable residency visa — an increasingly popular benefit.',
    ],
    bodyTr: [
      'Dubai\'da yabancı yatırımcı olarak mülk satın almak, birçok uluslararası piyasaya kıyasla son derece sadeleştirilmiş bir süreçtir. Dubai Arazi Departmanı (DLD), tüm işlemleri denetler ve bürokratik gecikmeleri önemli ölçüde azaltan şeffaf, dijitalleştirilmiş bir sistem sürdürür.',
      'Süreç, mülk seçimi ve genellikle %5-10 peşinatla güvence altına alınan bir rezervasyonla başlar. Plan öncesi alımlarda, inşaat aşamalarına göre yapılandırılmış bir ödeme planıyla bir Satış ve Satın Alma Sözleşmesi (SPA) imzalanır.',
      'Tamamlanmış mülkler için işlem, geliştiriciden bir İtiraz Yok Belgesi (NOC) alınması — bekleyen hizmet bedeli olmadığının onaylanması — ve ardından Dubai Arazi Departmanı\'nda tapu devrini kapsar. DLD, varsayılan olarak alıcı ve satıcı arasında eşit bölünen %4 devir ücreti almaktadır.',
      'Hazır bir mülk için toplam işlem süresi, anlaşmadan tapu devrine kadar genellikle 2-4 haftadır. Uluslararası alıcılar satın almak için BAE oturma izni vizesi gerektirmez, ancak 750.000 AED ve üzeri değerindeki mülkler, sahibini yenilenebilir bir oturma vizesine hak kazandırabilir.',
    ],
    category: 'Dubai Real Estate',
    categoryTr: 'Dubai Gayrimenkul',
    ctaType: 'soft',
    ctaText: 'Explore options',
    ctaTextTr: 'Seçenekleri keşfedin',
    image: '/guides/mario-gogh-VBLHICVh-lI-unsplash.jpg',
  },
  {
    id: 8,
    slug: 'countries-offering-residency-by-investment',
    title: 'Which Countries Offer Residency by Investment?',
    titleTr: 'Hangi Ülkeler Yatırım ile Oturum İzni Sunuyor?',
    excerpt: 'A comprehensive overview of the most popular residency-by-investment programmes available worldwide.',
    excerptTr: 'Dünya genelinde mevcut en popüler yatırım yoluyla oturum programlarına kapsamlı bir bakış.',
    bodyEn: [
      'Residency by investment programmes — sometimes called "golden visas" — allow individuals to obtain temporary or permanent residency in a foreign country by making a qualifying economic contribution. These programmes have proliferated globally over the past decade, driven by rising demand for international mobility, tax planning flexibility and lifestyle diversification.',
      'In Europe, Portugal, Greece, Spain and Malta remain the most established options. Portugal\'s programme (revised in 2024) now focuses on venture capital fund investments from €500,000, while Greece offers one of the lowest entry points at €250,000 for real estate in most areas. Spain\'s programme requires a minimum €500,000 property investment, and Malta offers both residency and citizenship pathways.',
      'The UAE has emerged as a leading destination with its Golden Visa programme, offering 10-year renewable residency for property investments of AED 2 million or more. The programme\'s appeal is enhanced by the UAE\'s zero income tax regime, world-class infrastructure and strategic location between Europe and Asia.',
      'The Caribbean nations — including St Kitts and Nevis, Antigua and Barbuda, Dominica and Grenada — offer citizenship-by-investment programmes starting from approximately $100,000 in donations or $200,000 in real estate. These provide visa-free access to 140+ countries and attractive tax environments. Selection should be guided by your specific goals: Schengen access, tax optimisation, lifestyle or legacy planning.',
    ],
    bodyTr: [
      'Yatırım yoluyla oturum programları — bazen "altın vize" olarak da adlandırılır — bireylerin nitelikli bir ekonomik katkı yaparak yabancı bir ülkede geçici veya kalıcı oturma izni elde etmesine olanak tanır.',
      'Avrupa\'da Portekiz, Yunanistan, İspanya ve Malta en köklü seçenekler olmaya devam etmektedir. Portekiz\'in programı (2024\'te revize edilmiş) artık 500.000 €\'dan başlayan girişim sermayesi fonu yatırımlarına odaklanırken, Yunanistan çoğu bölgede 250.000 €\'luk gayrimenkul ile en düşük giriş noktalarından birini sunmaktadır.',
      'BAE, Altın Vize programıyla öncü bir destinasyon olarak öne çıkmıştır; 2 milyon AED ve üzeri mülk yatırımları için 10 yıllık yenilenebilir oturma izni sunmaktadır.',
      'Karayip ülkeleri — St Kitts ve Nevis, Antigua ve Barbuda, Dominika ve Grenada dahil — yaklaşık 100.000 $ bağış veya 200.000 $ gayrimenkulden başlayan yatırım yoluyla vatandaşlık programları sunmaktadır. Seçim, belirli hedeflerinize göre yönlendirilmelidir.',
    ],
    category: 'Residency by Investment',
    categoryTr: 'Yatırım ile Oturum',
    ctaType: 'hard',
    ctaText: 'Book free consultation',
    ctaTextTr: 'Ücretsiz danışmanlık randevusu alın',
    image: '/guides/global-residence-index-D01GwcpNt0c-unsplash.jpg',
  },
  {
    id: 9,
    slug: 'eu-vs-usa-residency-comparison',
    title: 'EU vs USA Residency by Investment: A Comparison',
    titleTr: 'AB ve ABD Yatırım ile Oturum Karşılaştırması',
    excerpt: 'Comparing European golden visa programmes with the US EB-5 investor visa — costs, timelines and benefits.',
    excerptTr: 'Avrupa altın vize programları ile ABD EB-5 yatırımcı vizesinin karşılaştırması — maliyetler, süreler ve avantajlar.',
    bodyEn: [
      'For high-net-worth individuals seeking residency through investment, Europe and the United States represent the two most significant destinations. Each region offers distinct advantages and structures, and the optimal choice depends heavily on your personal circumstances, mobility needs and financial objectives.',
      'European golden visa programmes generally offer faster processing times (3–6 months for initial approval in most jurisdictions), lower minimum investments (€250,000–€500,000 in most countries) and the significant advantage of Schengen zone mobility — allowing free movement across 27 European countries. Physical presence requirements tend to be minimal, often just 7–14 days per year.',
      'The US EB-5 programme requires a minimum investment of $800,000 in a Targeted Employment Area (TEA) or $1,050,000 elsewhere, with the additional requirement that the investment creates at least 10 full-time jobs. Processing times are longer — typically 24–36 months — but the programme leads directly to a US Green Card, offering permanent residency and, after five years, a pathway to US citizenship.',
      'Tax implications differ substantially. European programmes like Portugal\'s NHR regime can offer favourable tax treatment for new residents, while US residency subjects worldwide income to federal taxation. This makes pre-immigration tax planning essential for US-bound investors. Our team works with specialist advisors in both regions to ensure clients make fully informed decisions aligned with their broader wealth planning strategy.',
    ],
    bodyTr: [
      'Yüksek net değere sahip bireyler için yatırım yoluyla oturum konusunda Avrupa ve Amerika Birleşik Devletleri en önemli iki destinasyonu temsil etmektedir. Her bölge farklı avantajlar ve yapılar sunmaktadır.',
      'Avrupa altın vize programları genellikle daha hızlı işlem süreleri (3-6 ay), daha düşük minimum yatırımlar (250.000-500.000 €) ve Schengen bölgesi mobilitesinin önemli avantajını sunar — 27 Avrupa ülkesinde serbest dolaşım sağlar.',
      'ABD EB-5 programı, Hedeflenen İstihdam Bölgesi\'nde (TEA) minimum 800.000 $ veya diğer bölgelerde 1.050.000 $ yatırım gerektirmekte olup yatırımın en az 10 tam zamanlı istihdam yaratması gerekmektedir. İşlem süreleri daha uzundur — genellikle 24-36 ay.',
      'Vergi etkileri önemli ölçüde farklılık gösterir. Portekiz\'in NHR rejimi gibi Avrupa programları yeni mukimler için avantajlı vergi muamelesi sunabilirken, ABD oturma izni dünya genelindeki geliri federal vergilendirmeye tabi kılar. Bu durum, ABD\'ye yönelik yatırımcılar için göç öncesi vergi planlamasını zorunlu kılar.',
    ],
    category: 'Residency by Investment',
    categoryTr: 'Yatırım ile Oturum',
    ctaType: 'soft',
    ctaText: 'Learn more about your options',
    ctaTextTr: 'Seçenekleriniz hakkında daha fazla bilgi edinin',
    image: '/guides/obi-pVvZ2bnqJ94-unsplash.jpg',
  },
  {
    id: 10,
    slug: 'minimum-investment-amounts-residency',
    title: 'Minimum Investment Amounts for Residency Programmes',
    titleTr: 'Oturum Programları İçin Minimum Yatırım Tutarları',
    excerpt: 'A comparison of minimum investment thresholds across the world\'s leading residency-by-investment programmes.',
    excerptTr: 'Dünyanın önde gelen yatırım yoluyla oturum programlarındaki minimum yatırım eşiklerinin karşılaştırması.',
    bodyEn: [
      'Investment thresholds for residency programmes vary widely by country, investment type and the specific benefits offered. Understanding the landscape of minimum amounts helps investors identify programmes that align with both their budget and their strategic objectives.',
      'At the lower end, programmes like Greece (€250,000 real estate) and Dominica ($100,000 donation) offer accessible entry points with meaningful benefits. Mid-range options include Portugal (€500,000 fund investment), Spain (€500,000 real estate) and the UAE Golden Visa (AED 2 million property). Premium programmes such as the UK Innovator Founder Visa and US EB-5 ($800,000–$1,050,000) require larger commitments but provide access to the world\'s largest economies.',
      'The investment type significantly affects the risk-return profile. Real estate investments offer tangible assets with potential appreciation and rental income. Fund investments provide diversification but require trust in fund management. Donations offer the simplest structure but no financial return. Business investments combine residency benefits with entrepreneurial opportunity but carry higher operational risk.',
      'Beyond the headline investment amount, applicants should budget for ancillary costs including government fees, legal fees, due diligence costs and ongoing compliance requirements. These can add 5–15% to the total programme cost depending on the jurisdiction. Our advisory team provides a comprehensive cost analysis for each programme to ensure there are no surprises during the application process.',
    ],
    bodyTr: [
      'Oturum programları için yatırım eşikleri ülkeye, yatırım türüne ve sunulan belirli avantajlara göre büyük farklılıklar gösterir. Minimum tutarların görünümünü anlamak, yatırımcıların hem bütçeleri hem stratejik hedefleriyle uyumlu programları belirlemesine yardımcı olur.',
      'Alt sınırda Yunanistan (250.000 € gayrimenkul) ve Dominika (100.000 $ bağış) gibi programlar erişilebilir giriş noktaları sunar. Orta sınıf seçenekler arasında Portekiz (500.000 € fon yatırımı), İspanya (500.000 € gayrimenkul) ve BAE Altın Vize (2 milyon AED mülk) yer almaktadır.',
      'Yatırım türü, risk-getiri profilini önemli ölçüde etkiler. Gayrimenkul yatırımları değer artışı ve kira geliri potansiyeli olan somut varlıklar sunar. Fon yatırımları çeşitlendirme sağlar ancak fon yönetimine güven gerektirir.',
      'Başlık yatırım tutarının ötesinde, başvuru sahipleri hükümet ücretleri, hukuki ücretler, durum tespiti maliyetleri ve devam eden uyumygereklilikleri dahil ek maliyetleri bütçelemelidir. Bunlar, yargı yetkisine bağlı olarak toplam program maliyetine %5-15 ekleyebilir.',
    ],
    category: 'Residency by Investment',
    categoryTr: 'Yatırım ile Oturum',
    ctaType: 'inline',
    ctaText: 'Want a personalised investment breakdown?',
    ctaTextTr: 'Kişiselleştirilmiş bir yatırım analizi ister misiniz?',
    image: '/guides/photo-1554224155-6726b3ff858f.jpeg',
  },
  {
    id: 11,
    slug: 'how-to-enter-uk-market',
    title: 'How to Enter the UK Market as a Foreign Business',
    titleTr: 'Yabancı Bir İşletme Olarak İngiltere Pazarına Nasıl Girilir?',
    excerpt: 'A practical guide for international businesses looking to establish a presence in the United Kingdom.',
    excerptTr: 'İngiltere\'de varlık kurmak isteyen uluslararası işletmeler için pratik bir rehber.',
    bodyEn: [
      'The United Kingdom remains one of Europe\'s most attractive markets for international business expansion, offering a transparent regulatory environment, access to world-class financial services, a highly skilled workforce and strong legal protections for businesses and investors. London, in particular, serves as a global hub for finance, technology, professional services and creative industries.',
      'The first step is typically establishing a UK legal entity — most commonly a Private Limited Company (Ltd) registered with Companies House. The registration process can be completed within 24 hours and requires a registered UK office address, at least one director and one shareholder. There are no nationality requirements for directors or shareholders, making the structure fully accessible to international entrepreneurs.',
      'Beyond company formation, market entry strategy should address key practical considerations: opening a UK business bank account, understanding corporate tax obligations (currently 25% for profits above £250,000), registering for VAT if applicable, and securing any sector-specific licences or regulatory approvals. Immigration considerations — particularly the Innovator Founder Visa — should also be factored into early planning.',
      'Cultural and commercial due diligence is equally important. Understanding UK business etiquette, contract law conventions and consumer expectations can meaningfully impact market entry success. Building relationships with local partners, industry associations and professional networks accelerates market penetration and helps navigate the nuanced aspects of a new business environment.',
    ],
    bodyTr: [
      'İngiltere, şeffaf düzenleme ortamı, dünya standartında finansal hizmetlere erişim, yüksek nitelikli iş gücü ve işletme ve yatırımcılar için güçlü yasal korumalarla uluslararası iş genişlemesi için Avrupa\'nın en cazip piyasalarından biri olmaya devam etmektedir.',
      'İlk adım genellikle bir İngiltere tzel kişiliği kurmaktır — en yaygın olarak Companies House\'a kayıtlı bir özel limited şirket (Ltd). Kayıt işlemi 24 saat içinde tamamlanabilir ve kayıtlı bir İngiltere ofis adresi, en az bir yönetim kurulu üyesi ve bir hissedar gerektirir.',
      'Şirket kuruluşunun ötesinde, pazar giriş stratejisi şu önemli pratik hususları ele almalıdır: İngiltere işletme banka hesabı açmak, kurumlar vergisi yükümlülüklerini anlamak, KDV kaydı yapmak ve sektöre özgü lisans veya düzenleme onaylarını sağlamak.',
      'Kültürel ve ticari durum tespiti de bir o kadar önemlidir. İngiltere iş âdâbını, sözleşme hukuku geleneklerini ve tüketici beklentilerini anlamak, pazar giriş başarısını önemli ölçüde etkileyebilir.',
    ],
    category: 'Business Expansion',
    categoryTr: 'İş Geliştirme',
    ctaType: 'hard',
    ctaText: 'Get investment plan',
    ctaTextTr: 'Yatırım planı alın',
    image: '/guides/adeolu-eletu-E7RLgUjjazc-unsplash.jpg',
  },
  {
    id: 12,
    slug: 'setting-up-company-uk',
    title: 'Setting Up a Company in the UK: Step-by-Step',
    titleTr: 'İngiltere\'de Şirket Kuruluşu: Adım Adım Rehber',
    excerpt: 'Everything international entrepreneurs need to know about forming and running a UK limited company.',
    excerptTr: 'Uluslararası girişimcilerin İngiltere\'de limited şirket oluşturma ve yönetme hakkında bilmesi gereken her şey.',
    bodyEn: [
      'Forming a company in the United Kingdom is one of the simplest and most cost-effective processes globally. Companies House, the UK\'s registrar of companies, facilitates online registration that can be completed in as little as 24 hours. The most common structure for international entrepreneurs is a Private Limited Company (Ltd), which offers limited liability protection and a familiar corporate framework for conducting business.',
      'Registration requires a company name (which must be unique and not misleading), a registered office address in the UK, at least one director and at least one shareholder. The Memorandum of Association and Articles of Association — the company\'s constitutional documents — are filed at incorporation. Standard model articles are available for most business types.',
      'Post-incorporation essentials include registering for Corporation Tax with HMRC within three months, opening a UK business bank account, registering for VAT if your taxable turnover exceeds £85,000, and setting up a PAYE scheme if employing staff. A UK accountant experienced in international business structures is strongly recommended.',
      'For non-UK based directors, practical considerations include arranging a registered UK business address, appointing a company secretary (not legally required but advisable), and maintaining statutory records including the PSC (Persons with Significant Control) register. Annual obligations include filing confirmation statements and annual accounts with Companies House, and Corporation Tax returns with HMRC.',
    ],
    bodyTr: [
      'İngiltere\'de şirket kurmak, küresel olarak en basit ve en uygun maliyetli süreçlerden biridir. Companies House, 24 saat içinde tamamlanabilen çevrimiçi kayıt kolaylığı sağlar. Uluslararası girişimciler için en yaygın yapı özel limited şirkettir (Ltd).',
      'Kayıt için bir şirket adı (benzersiz ve yanıltıcı olmayan), İngiltere\'de kayıtlı bir ofis adresi, en az bir yönetim kurulu üyesi ve en az bir hissedar gerekmektedir. Kurucu Sözleşme ve Ana Sözleşme — şirketin anayasal belgeleri — kuruluş sırasında dosyalanır.',
      'Kuruluş sonrası temel gereksinimler arasında üç ay içinde HMRC\'ye kurumlar vergisi kaydı yapmak, İngiltere işletme banka hesabı açmak, vergilendirilebilir cironuz 85.000 £\'u aşarsa KDV kaydı yapmak ve personel çalıştırılacaksa PAYE şeması kurmak yer almaktadır.',
      'İngiltere dışında yerleşik yöneticiler için pratik hususlar arasında kayıtlı bir İngiltere iş adresi düzenleme, şirket sekreteri atama (yasal olarak zorunlu değil ancak tavsiye edilir) ve PSC kaydı dahil yasal kayıtları tutmak yer almaktadır.',
    ],
    category: 'Business Expansion',
    categoryTr: 'İş Geliştirme',
    ctaType: 'soft',
    ctaText: 'Learn more',
    ctaTextTr: 'Daha fazla bilgi edinin',
    image: '/guides/charlesdeluvio-Lks7vei-eAg-unsplash.jpg',
  },
  {
    id: 13,
    slug: 'finding-local-partners-uk',
    title: 'Finding Local Partners for Business Expansion in the UK',
    titleTr: 'İngiltere\'de İş Geliştirme İçin Yerel Ortaklar Bulmak',
    excerpt: 'How to identify, evaluate and partner with UK-based businesses and professionals for successful market entry.',
    excerptTr: 'Başarılı pazar girişi için İngiltere merkezli işletmeler ve profesyonellerle nasıl ortaklık kurulur.',
    bodyEn: [
      'Building the right local partnerships is frequently the decisive factor in successful international business expansion. In the UK market, where relationships, reputation and trust carry significant weight, having credible local partners can accelerate market entry, reduce operational risk and provide invaluable cultural and commercial insights.',
      'Potential partnership models include joint ventures, distribution agreements, franchise arrangements, strategic alliances and equity partnerships. The right model depends on your industry, capital structure and how much operational control you wish to retain. Joint ventures are common in property development and financial services, while distribution or agency agreements suit product-based businesses.',
      'Identifying suitable partners involves a combination of industry research, trade show attendance, professional network referrals and targeted outreach. The Department for Business and Trade (DBT) offers free support services for international businesses, including partner matching and market intelligence. Industry associations such as the CBI, FSB and sector-specific bodies are also valuable networking channels.',
      'Due diligence on potential partners should cover financial health, regulatory standing, market reputation and cultural compatibility. Taking time to understand a partner\'s track record, client portfolio and strategic vision helps ensure alignment and reduces the risk of partnership dissolution. Our team assists international businesses with partner identification, due diligence coordination and introductions across our professional network in the UK.',
    ],
    bodyTr: [
      'Doğru yerel ortaklıklar kurmak, başarılı uluslararası iş genişlemesinde sıklıkla belirleyici faktördür. İlişkilerin, itibarın ve güvenin önemli ağırlık taşıdığı İngiltere piyasasında güvenilir yerel ortaklara sahip olmak pazar girişini hızlandırabilir.',
      'Potansiyel ortaklık modelleri arasında ortak girişimler, dağıtım anlaşmaları, franchise düzenlemeleri, stratejik ittifaklar ve öz sermaye ortaklıkları yer almaktadır. Doğru model, sektörünüze, sermaye yapınıza ve ne kadar operasyonel kontrol elinde tutmak istediğinize bağlıdır.',
      'Uygun ortakları belirlemek; sektör araştırması, ticaret fuarına katılım, profesyonel ağ yönlendirmeleri ve hedefli erişimin bir kombinasyonunu içerir. İşletme ve Ticaret Departmanı (DBT), ortak eşleştirme ve pazar istihbaratı dahil uluslararası işletmelere ücretsiz destek hizmetleri sunmaktadır.',
      'Potansiyel ortaklar üzerinde durum tespiti; finansal sağlık, düzenleme durumu, piyasa itibarı ve kültürel uyumluluğu kapsamalıdır. Bir ortağın geçmiş performansını, müşteri portföyünü ve stratejik vizyonunu anlamak için zaman ayırmak, uyumu sağlar ve ortaklık fesih riskini azaltır.',
    ],
    category: 'Business Expansion',
    categoryTr: 'İş Geliştirme',
    ctaType: 'hard',
    ctaText: 'Book free consultation',
    ctaTextTr: 'Ücretsiz danışmanlık randevusu alın',
    image: '/guides/campaign-creators-gMsnXqILjp4-unsplash.jpg',
  },
];

export function getGuideBySlug(slug: string): Guide | undefined {
  return guides.find((g) => g.slug === slug);
}
