export interface PropertyData {
  slug: string;
  name: string;
  developer: string;
  location: string;
  fullAddress: string;
  region: 'UK' | 'UAE';
  city: 'london' | 'dubai';
  price: string;
  priceNote: { en: string; tr: string };
  completion: string;
  beds: string;
  floors?: string;
  totalUnits?: string;
  lat: number;
  lng: number;
  heroImage: string;
  images: string[];
  description: { en: string; tr: string };
  highlights: { en: string[]; tr: string[] };
  amenities: string[];
}

export const allProperties: PropertyData[] = [
  // ──────────────────────── LONDON ────────────────────────
  {
    slug: 'westminster-tower',
    name: 'Westminster Tower',
    developer: 'London Square',
    location: 'SE1 7SP, London',
    fullAddress: '3 Albert Embankment, London SE1 7SP, UK',
    region: 'UK',
    city: 'london',
    price: '£550,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    completion: 'Q2 2026',
    beds: '1–3 Bed',
    floors: '30',
    totalUnits: '218',
    lat: 51.4988,
    lng: -0.0988,
    heroImage: '/images/properties/london/westminster-tower/4296-westminster-tower-view-01-hummingbird-sunset-04-dfrc-final.jpg',
    images: [
      '/images/properties/london/westminster-tower/4296-westminster-tower-view-01-hummingbird-sunset-04-dfrc-final.jpg',
      '/images/properties/london/westminster-tower/4296-westminster-tower-view-01-ground-level-dusk-004-dfrc-final.jpg',
      '/images/properties/london/westminster-tower/4296-hummingbird-kv-draft02-df-final.jpg',
      '/images/properties/london/westminster-tower/4296-westminster-tower-kv-wintergarden-008-ctdf-final.jpg',
      '/images/properties/london/westminster-tower/4296-westminster-tower-living-draft07-dfct-final.jpg',
      '/images/properties/london/westminster-tower/4296-westminster-tower-int-winter-garden-light-opt-draft08-dfct-final.jpg',
      '/images/properties/london/westminster-tower/4296-westminster-tower-kitchen-light-draft06-dfct-final.jpg',
      '/images/properties/london/westminster-tower/4296-westminster-tower-kitchen-dark-draft06-dfct-final.jpg',
      '/images/properties/london/westminster-tower/4296-westminster-tower-bedroom-light-final.jpg',
      '/images/properties/london/westminster-tower/4296-westminster-tower-bedroom-dark-final.jpg',
      '/images/properties/london/westminster-tower/4296-westminster-tower-bathroom-wide-light-draft06-dfct-final.jpg',
      '/images/properties/london/westminster-tower/4296-westminster-tower-bathroom-wide-dark-draft06-dfct-final.jpg',
    ],
    description: {
      en: 'Westminster Tower is a prestigious riverside development on the iconic Albert Embankment in London SE1, offering spectacular views of the River Thames and the Houses of Parliament. Designed by London Square, this 30-storey landmark combines contemporary architecture with premium finishes to deliver an unrivalled urban living experience in the heart of the capital.\n\nResidents benefit from a prime Zone 1 location with effortless access to Westminster, Waterloo, Vauxhall and the City, making it an ideal choice for both owner-occupiers and investors seeking strong rental demand and long-term capital growth.',
      tr: 'Westminster Tower, Londra SE1\'de, Albert Embankment üzerinde konumlanan seçkin bir nehir kenarı projesidir. Parlamento ve Thames Nehri\'ne uzanan kesintisiz manzaralarıyla öne çıkan bu 30 katlı yapı, London Square imzası taşıyor ve modern mimariyi özenle tasarlanmış premium iç mekânlarla buluşturuyor.\n\nSakinlerine Westminster, Waterloo, Vauxhall ve City bölgelerine hızlı ve kolay erişim sunan merkezi konumu sayesinde; hem şehir yaşamını tercih eden alıcılar hem de güçlü kira talebi ve uzun vadeli değer artışı hedefleyen yatırımcılar için ayrıcalıklı bir fırsat sunmaktadır.',
    },
    highlights: {
      en: [
        'Prime Zone 1 riverside location on Albert Embankment',
        'Panoramic Thames and Parliament views',
        '30 storeys with 218 luxury apartments',
        '24-hour concierge and security',
        'Moments from Vauxhall and Westminster stations',
        'Strong rental yield driven by proximity to government quarter',
      ],
      tr: [
        'Albert Embankment üzerinde, 1. bölgede ayrıcalıklı nehir kenarı konumu',
        'Thames Nehri ve Parlamento\'ya uzanan panoramik manzaralar',
        '218 seçkin daireden oluşan, 30 katlı modern yapı',
        '24 saat concierge ve güvenlik hizmeti',
        'Vauxhall ve Westminster ulaşım hatlarına yakın konum',
        'Merkezi ve prestijli lokasyonu sayesinde güçlü kira potansiyeli',
      ],
    },
    amenities: ['24hr Concierge', 'Residents Lounge', 'Gym & Wellness', 'Rooftop Terrace', 'Cycle Storage', 'Secure Parking'],
  },
  {
    slug: 'ransomes-wharf',
    name: "Ransome's Wharf",
    developer: 'London Square',
    location: 'SW11, London',
    fullAddress: "Ransome's Wharf, Battersea, London SW11, UK",
    region: 'UK',
    city: 'london',
    price: '£725,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    completion: 'Q4 2026',
    beds: '1–3 Bed',
    floors: '12',
    totalUnits: '152',
    lat: 51.4806,
    lng: -0.1694,
    heroImage: '/images/properties/london/ransomes-wharf/rsw-ext-dusk-hero-final-2k.jpg',
    images: [
      '/images/properties/london/ransomes-wharf/rsw-ext-dusk-hero-final-2k.jpg',
      '/images/properties/london/ransomes-wharf/rsw-ext-hero2-final-2k.jpg',
      '/images/properties/london/ransomes-wharf/rsw-ext-hummingbird-final-2k.jpg',
      '/images/properties/london/ransomes-wharf/rsw-ext-courtyard-plaza-final-2k.jpg',
      '/images/properties/london/ransomes-wharf/rsw-ext-dock-final-2k.jpg',
      '/images/properties/london/ransomes-wharf/rsw-ext-dock-no-talent-final-2k.jpg',
      '/images/properties/london/ransomes-wharf/rsw-ext-terrace-final-2k.jpg',
      '/images/properties/london/ransomes-wharf/rsw-ext-closeup-final-2k.jpg',
      '/images/properties/london/ransomes-wharf/rsw-ext-cowork-final-2k.jpg',
      '/images/properties/london/ransomes-wharf/rsw-ext-deli-final-2k.jpg',
      '/images/properties/london/ransomes-wharf/rsw-int-living-dining-final-2k.jpg',
      '/images/properties/london/ransomes-wharf/rsw-int-08akitchen-final-2k.jpg',
      '/images/properties/london/ransomes-wharf/rsw-int-14ekitchen-final-2k.jpg',
      '/images/properties/london/ransomes-wharf/rsw-int-18cbedroom-final-2k.jpg',
      '/images/properties/london/ransomes-wharf/rsw-int-21dbedroom-final-2k.jpg',
      '/images/properties/london/ransomes-wharf/rsw-int-ensuite-final-2k.jpg',
    ],
    description: {
      en: "Ransome's Wharf is an exceptional waterfront development set along the banks of the River Thames in Battersea, SW11. Designed by London Square, this boutique collection of 152 apartments delivers refined contemporary living in one of London's most sought-after neighbourhoods.\n\nFrom generous private balconies and terraces overlooking the river, to refined interiors crafted with the finest materials, every detail at Ransome's Wharf has been meticulously considered. Residents enjoy direct access to the vibrant South Bank, Chelsea Bridge Wharf and the extensive green spaces of Battersea Park.",
      tr: "Ransome's Wharf, Battersea SW11'de, nehre yürüme mesafesinde ve rıhtım hattı boyunca konumlanan seçkin bir projedir. London Square tarafından geliştirilen bu butik koleksiyon, 152 daireden oluşmakta olup Londra'nın öne çıkan yaşam bölgelerinden birinde modern ve rafine bir yaşam sunar.\n\nGeniş özel balkon ve teraslar, özenle seçilmiş malzemelerle tasarlanmış iç mekânlar ve detaylara verilen önem, projeyi ayrıcalıklı kılar. Sakinler; South Bank'in canlı atmosferine, Chelsea Bridge'e ve Battersea Park'ın yeşil alanlarına kolay erişim imkânından faydalanır.",
    },
    highlights: {
      en: [
        'Exclusive Thames waterfront location in Battersea',
        'Private balconies and terraces with river views',
        'Boutique development of 152 luxury apartments',
        "Walking distance to Battersea Park and King's Road",
        'Convenient access to National Rail and underground',
        'Premium specification throughout',
      ],
      tr: [
        'Battersea\'da, nehre yürüme mesafesinde ve rıhtım hattı boyunca ayrıcalıklı konum',
        'Nehir manzarasına sahip geniş özel balkon ve teraslar',
        '152 seçkin daireden oluşan butik proje',
        'Battersea Parkı ve King\'s Road\'a kısa yürüyüş mesafesi',
        'Tren ve metro hatlarına kolay erişim',
        'Tüm dairelerde yüksek standartlı teknik donanım ve kaliteli iç mekân detayları',
      ],
    },
    amenities: ['River Views', 'Private Balconies', 'Concierge', 'Residents Lounge', 'Cycle Storage', 'Landscaped Gardens'],
  },
  {
    slug: 'woolwich-central',
    name: 'Woolwich Central',
    developer: 'London Square',
    location: 'SE18, London',
    fullAddress: 'Woolwich, London SE18, UK',
    region: 'UK',
    city: 'london',
    price: '£380,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    completion: 'Q1 2027',
    beds: '1–2 Bed',
    floors: '15',
    totalUnits: '193',
    lat: 51.4913,
    lng: 0.0672,
    heroImage: '/images/properties/london/woolwich-central/250312-woolwichcentral-ground-level-hero-final-2k.jpg',
    images: [
      '/images/properties/london/woolwich-central/250312-woolwichcentral-ground-level-hero-final-2k.jpg',
      '/images/properties/london/woolwich-central/241211-woolwich-central-ground-level-hero-sketch-final-2k.jpg',
      '/images/properties/london/woolwich-central/241211-woolwich-central-ground-level-hero-sketch-lookup-final-2k.jpg',
      '/images/properties/london/woolwich-central/250312-woolwichcentral-lobby-final-2k.jpg',
      '/images/properties/london/woolwich-central/250312-woolwichcentral-lounge-final-2k.jpg',
      '/images/properties/london/woolwich-central/241211-woolwich-central-entrance-final-2k.jpg',
      '/images/properties/london/woolwich-central/241211-woolwich-central-living-baseline-final-2k.jpg',
      '/images/properties/london/woolwich-central/241211-woolwich-central-kitchen-baseline-final-2k.jpg',
      '/images/properties/london/woolwich-central/241211-woolwich-central-bedroom-baseline-final-2k.jpg',
      '/images/properties/london/woolwich-central/241211-woolwich-central-bathroom-baseline-final-2k.jpg',
      '/images/properties/london/woolwich-central/250312-woolwich-central-ext-balcony-final-2k.jpg',
      '/images/properties/london/woolwich-central/250312-woolwich-central-ext-balcony-no-people-final-2k.jpg',
      '/images/properties/london/woolwich-central/250312-woolwich-central-roof-terrace-final-2k.jpg',
    ],
    description: {
      en: "Woolwich Central represents an outstanding investment opportunity in one of London's most rapidly regenerating areas. Located in the heart of Woolwich SE18, this development benefits from the Elizabeth Line (Crossrail) rail connection, which dramatically reduces journey times to central London and significantly increases property values.\n\nWith a target rental yield of 5.5% and entry pricing from £380,000, Woolwich Central offers excellent affordability relative to inner-London alternatives, alongside strong projected capital growth driven by ongoing regeneration investment in the Royal Borough of Greenwich.",
      tr: 'Woolwich Central, Londra\'nın hızla değer kazanan bölgelerinden biri olan Woolwich\'te, dikkat çekici bir yatırım fırsatı sunar. SE18\'in merkezinde konumlanan proje, Elizabeth Line bağlantısı sayesinde merkezi Londra\'ya hızlı erişim imkânı sağlayarak bölgenin erişilebilirliğini ve yatırım potansiyelini önemli ölçüde artırmaktadır.\n\nRekabetçi başlangıç fiyatları ve güçlü kira potansiyeliyle öne çıkan Woolwich Central, merkezi Londra\'daki alternatiflere kıyasla daha erişilebilir bir yatırım imkânı sunarken; Greenwich bölgesinde devam eden kapsamlı dönüşüm projeleri sayesinde uzun vadeli değer artışı açısından da güçlü bir perspektif sunmaktadır.',
    },
    highlights: {
      en: [
        'Direct Elizabeth Line (Crossrail) access',
        'Prices from £380,000 — strong affordability',
        '5.5% projected rental yield',
        'Part of major Woolwich regeneration programme',
        'Zone 3 — fast connections to Canary Wharf and Bond Street',
        'High rental demand from tech and finance professionals',
      ],
      tr: [
        'Elizabeth Line ile doğrudan ve hızlı ulaşım imkânı',
        'Rekabetçi başlangıç fiyatlarıyla yüksek erişilebilirlik',
        'Güçlü kira potansiyeli',
        'Woolwich bölgesindeki kapsamlı dönüşüm sürecinin parçası',
        'Zone 3\'te konum, Canary Wharf ve Bond Street\'e hızlı bağlantı',
        'Teknoloji ve finans sektöründen güçlü kiracı talebi',
      ],
    },
    amenities: ['Elizabeth Line Hub', 'Residents Gym', 'Concierge', 'Roof Terrace', 'Secure Parking', 'Private Courtyard'],
  },
  {
    slug: 'prince-of-wales-drive',
    name: 'Prince Of Wales Drive',
    developer: 'Berkeley Group',
    location: 'SW11 4FA, London',
    fullAddress: 'Prince of Wales Drive, Battersea, London SW11 4FA, UK',
    region: 'UK',
    city: 'london',
    price: '£850,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    completion: 'Ready to Move',
    beds: '1–3 Bed',
    floors: '18',
    totalUnits: '264',
    lat: 51.4757,
    lng: -0.1442,
    heroImage: '/images/properties/london/prince-of-wales-drive-1.jpeg',
    images: [
      '/images/properties/london/prince-of-wales-drive-1.jpeg',
      '/images/properties/london/prince-of-wales-drive-2.jpeg',
      '/images/properties/london/prince-of-wales-drive-3.jpeg',
      'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?q=80&w=900',
    ],
    description: {
      en: "Prince of Wales Drive is a landmark Berkeley Group development set opposite Battersea Park, one of London's most beloved green spaces. Perfectly positioned in SW11, one of the capital's most prestigious residential postcodes, this collection of beautifully designed apartments features generous proportions, premium specification and unparalleled access to both the park and the vibrant cultural attractions of Chelsea, Sloane Square and the King's Road.\n\nAs a ready-to-move development with strong existing rental demand, Prince of Wales Drive offers investors immediate rental income potential alongside powerful long-term capital appreciation in a blue-chip Battersea location.",
      tr: 'Prince of Wales Drive, Battersea Park\'ın hemen karşısında konumlanan ve Berkeley Group imzası taşıyan seçkin bir konut projesidir. Londra\'nın en prestijli bölgelerinden biri olan SW11\'de yer alan bu daire koleksiyonu; ferah yaşam alanları, yüksek standartlı teknik donanım ve Battersea Park ile birlikte Chelsea, Sloane Square ve King\'s Road\'un sosyal ve kültürel yaşamına kolay erişim imkânı sunar.\n\nTeslime hazır yapısı ve güçlü kira talebi sayesinde proje, yatırımcılara anında kira geliri potansiyeli sunarken; Battersea\'nın öne çıkan konumu sayesinde uzun vadeli değer artışı açısından da güçlü bir yatırım fırsatı oluşturur.',
    },
    highlights: {
      en: [
        'Ready to move — immediate rental income potential',
        'Opposite iconic Battersea Park',
        'Blue-chip SW11 address',
        'Berkeley Group premium build quality',
        '5-minute walk to Battersea Power Station and Elizabeth Line',
        'Chelsea and South Kensington within easy reach',
      ],
      tr: [
        'Hazır teslim avantajı ile anında kira geliri potansiyeli',
        'Battersea Park\'ın hemen karşısında ayrıcalıklı konum',
        'Prestijli SW11 adresi',
        'Berkeley Group güvencesiyle yüksek inşaat kalitesi',
        'Battersea Power Station ve Elizabeth Line bağlantılarına kısa yürüyüş mesafesi',
        'Chelsea ve South Kensington\'a kolay erişim',
      ],
    },
    amenities: ['Park Views', 'Swimming Pool', 'Spa & Gym', '24hr Concierge', 'Secure Parking', 'Residents Garden'],
  },
  {
    slug: 'sterling-place',
    name: 'Sterling Place',
    developer: 'Barratt London',
    location: 'SW17 0SR, London',
    fullAddress: 'Sterling Place, Tooting, London SW17 0SR, UK',
    region: 'UK',
    city: 'london',
    price: '£420,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    completion: 'Q3 2026',
    beds: 'Studio–2 Bed',
    floors: '14',
    totalUnits: '168',
    lat: 51.4256,
    lng: -0.1718,
    heroImage: '/images/properties/london/sterling-place/4129-view-02-hummingbird-draft-002-diff-sky.jpg',
    images: [
      '/images/properties/london/sterling-place/4129-view-02-hummingbird-draft-002-diff-sky.jpg',
      '/images/properties/london/sterling-place/4129-view-01-podium-draft-002.jpg',
      '/images/properties/london/sterling-place/4129-view-03-elevated-from-the-north-angled-draft-002.jpg',
      '/images/properties/london/sterling-place/4129-view-04-street-level-dusk-draft-002.jpg',
      '/images/properties/london/sterling-place/4129-wimbledon-reach-ext-view-003-podium-elevated-draft-05-ab.jpg',
      '/images/properties/london/sterling-place/4129-wimbledon-reach-ext-view-004-podium-lawn-draft-03-ab.jpg',
      '/images/properties/london/sterling-place/4129-wimbledon-reach-ext-view-005-lifestyle-one-draft-03-ab.jpg',
      '/images/properties/london/sterling-place/4129-wimbledon-reach-ext-view-006-lifestyle-two-draft-03-ab.jpg',
      '/images/properties/london/sterling-place/cam9-static-3000x0100.jpg',
      '/images/properties/london/sterling-place/cam10-static-3000x0100.jpg',
      '/images/properties/london/sterling-place/cam11-static-3000x0100.jpg',
      '/images/properties/london/sterling-place/cam12-static-3000x0100.jpg',
      '/images/properties/london/sterling-place/gym-1.jpg',
    ],
    description: {
      en: "Sterling Place by Barratt London brings a new standard of contemporary urban living to the heart of Tooting, SW17. Sitting within an emerging residential hub that is attracting significant investment and regeneration, this development offers studios, one- and two-bedroom apartments that combine modern design, efficient layouts and high-quality specification.\n\nTooting's growing popularity among young professionals and families — driven by outstanding transport links including the Northern Line and National Rail, alongside an exceptional food and lifestyle scene — makes Sterling Place a compelling buy-to-let proposition with projected yields of 5%.",
      tr: 'Sterling Place, Barratt London imzasıyla, SW17 Tooting\'in merkezinde çağdaş şehir yaşamına yeni bir standart getiriyor. Gelişimini hızla sürdüren ve önemli yatırımlar çeken bu bölgede konumlanan proje; modern mimari, verimli planlanmış yaşam alanları ve yüksek kaliteli teknik özelliklerle stüdyo, 1 ve 2 odalı daire seçenekleri sunuyor.\n\nNorthern Line ve ulusal tren hatlarıyla güçlü ulaşım bağlantılarına sahip olan Tooting; canlı sosyal yaşamı, restoranları ve artan popülaritesiyle özellikle genç profesyoneller ve aileler için öne çıkıyor. Sterling Place, güçlü kira talebi ve dengeli fiyat seviyesiyle yatırımcılar için istikrarlı kira geliri ve uzun vadeli değer artışı potansiyeli sunmaktadır.',
    },
    highlights: {
      en: [
        'Excellent value entry point from £420,000',
        'Northern Line direct — city in under 30 minutes',
        'Tooting market and vibrant dining scene nearby',
        "One of South London's fastest-growing submarkets",
        '5.0% projected rental yield',
        'Modern specification with private outdoor space',
      ],
      tr: [
        'Rekabetçi başlangıç fiyatlarıyla güçlü bir giriş seviyesi fırsatı',
        'Northern Line ile şehir merkezine yaklaşık 30 dakikada doğrudan ulaşım',
        'Tooting Market ve bölgenin canlı gastronomi sahnesine yakın konum',
        'Güney Londra\'nın en hızlı gelişen konut bölgelerinden biri',
        'Dengeli kira potansiyeli',
        'Özel açık alanlar ve modern teknik donanım',
      ],
    },
    amenities: ['Roof Terrace', 'Residents Gym', 'Bike Storage', 'Communal Gardens', 'EV Charging', 'Video Entry'],
  },
  {
    slug: 'white-city-living',
    name: 'White City Living',
    developer: 'Berkeley Group',
    location: 'W12 7RQ, London',
    fullAddress: 'Westfield Avenue, White City, London W12 7RQ, UK',
    region: 'UK',
    city: 'london',
    price: '£650,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    completion: 'Ready to Move',
    beds: '1–3 Bed',
    floors: '22',
    totalUnits: '1,462',
    lat: 51.509,
    lng: -0.2332,
    heroImage: '/images/properties/london/white-city-living/01-westmont-and-landscape-with-fountains-v1633686647.jpg',
    images: [
      '/images/properties/london/white-city-living/01-westmont-and-landscape-with-fountains-v1633686647.jpg',
      '/images/properties/london/white-city-living/01-azalea-gardens-v1762766126.jpg',
      '/images/properties/london/white-city-living/02-westmont-v1633686686.jpg',
      '/images/properties/london/white-city-living/02-azalea-gardens-lounge-v1762766206.jpg',
      '/images/properties/london/white-city-living/01-whitecityliving-v1633687273.jpg',
      '/images/properties/london/white-city-living/02-whitecityliving-v1633687311.jpg',
      '/images/properties/london/white-city-living/06-whitecityliving-v1633687443.jpg',
      '/images/properties/london/white-city-living/06-westmont-concierge-v1762766484.jpg',
      '/images/properties/london/white-city-living/05-the-water-garden-lounge-v1762766422.jpg',
      '/images/properties/london/white-city-living/07-the-beach-club-v1762766545.jpg',
      '/images/properties/london/white-city-living/03-private-cinema-rooms-v1762766323.jpg',
      '/images/properties/london/white-city-living/04-private-games-rooms-v1762766371.jpg',
      '/images/properties/london/white-city-living/01-bh-wcl-interiors-00065-v1727102206-v1758191927.jpg',
      '/images/properties/london/white-city-living/02-bh-wcl-interiors-00161-v1727102270-v1758191934.jpg',
      '/images/properties/london/white-city-living/03-bh-wcl-interiors-00052-v1727102323-v1758191944.jpg',
      '/images/properties/london/white-city-living/04-bh-wcl-interiors-00116-v1727102382-v1758191950.jpg',
      '/images/properties/london/white-city-living/05-bh-wcl-interiors-00020-v1727102443-v1758191982.jpg',
      '/images/properties/london/white-city-living/06-bh-wcl-interiors-00144-v1727102501-v1758191959.jpg',
      '/images/properties/london/white-city-living/07-bh-wcl-interiors-00127-v1727102549-v1758191996.jpg',
      '/images/properties/london/white-city-living/08-bh-wcl-interiors-00002-v1727102605-v1758192018.jpg',
      '/images/properties/london/white-city-living/09-bh-wcl-interiors-00133-v1727102654-v1758192048.jpg',
      '/images/properties/london/white-city-living/solaris-one-and-two-v1727169280.jpg',
      '/images/properties/london/white-city-living/the-solaris-city-view-v1727169357.jpg',
      '/images/properties/london/white-city-living/the-solaris-entrance-v1727169482.jpg',
      '/images/properties/london/white-city-living/en-site-plan-0925-v1762763745.jpg',
    ],
    description: {
      en: "White City Living is Berkeley Group's flagship mixed-use development in West London, forming the centrepiece of the £8 billion White City regeneration. Situated at the doorstep of Westfield London — the largest urban shopping centre in Europe — and adjacent to the thriving Imperial College London campus, this landmark scheme redefines the concept of urban living.\n\nWith over 1,400 homes across a series of elegant towers, comprehensive on-site amenities and direct Underground access at Wood Lane station, White City Living offers investors exceptional connectivity, long-term capital growth potential and strong rental demand driven by proximity to major employment hubs in media, tech and academia.",
      tr: 'White City Living, Batı Londra\'da devam eden kapsamlı White City dönüşümünün merkezinde yer alan ve Berkeley Group tarafından geliştirilen seçkin bir karma yaşam projesidir. Westfield London\'a komşu konumu ve Imperial College London\'ın büyüyen kampüsüne yakınlığıyla, bölgenin en önemli yaşam ve yatırım merkezlerinden biri olarak öne çıkmaktadır.\n\nFarklı kuleler içinde konumlanan 1.400\'ün üzerinde konut, zengin sosyal olanaklar ve Wood Lane istasyonuna doğrudan erişim avantajı sunan proje; medya, teknoloji ve akademi alanlarındaki önemli iş merkezlerine yakınlığıyla dikkat çeker. White City Living, güçlü kira talebi ve bölgedeki dönüşümün etkisiyle uzun vadeli değer artışı potansiyeli sunan nitelikli bir yatırım fırsatıdır.',
    },
    highlights: {
      en: [
        'Heart of the £8 billion White City regeneration',
        'Next to Westfield London — Europe\'s largest urban mall',
        'Direct Circle & Hammersmith line access at Wood Lane',
        'Proximity to Imperial College London and BBC Media Village',
        "Berkeley Group's largest London development",
        'Strong long-term capital appreciation prospects',
      ],
      tr: [
        'White City bölgesindeki kapsamlı dönüşümün merkezinde stratejik konum',
        'Westfield London alışveriş merkezine komşu lokasyon',
        'Wood Lane istasyonundan Circle ve Hammersmith hatlarına doğrudan erişim',
        'Imperial College London ve BBC Media Village\'a yakınlık',
        "Berkeley Group'un Londra'daki en kapsamlı projelerinden biri",
        'Uzun vadede güçlü değer artışı potansiyeli',
      ],
    },
    amenities: ['Swimming Pool', 'Spa & Gym', '24hr Concierge', 'Cinema Room', 'Roof Garden', 'Private Dining'],
  },

  // ──────────────────────── DUBAI ────────────────────────
  {
    slug: 'binghatti-flare',
    name: 'Binghatti Flare',
    developer: 'Binghatti',
    location: 'Business Bay, Dubai',
    fullAddress: 'Business Bay, Dubai, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$380,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    completion: 'Q1 2027',
    beds: '1–3 Bed',
    floors: '35',
    totalUnits: '226',
    lat: 25.1858,
    lng: 55.2625,
    heroImage: '/images/properties/dubai/binghatti-flare/flare-exterior-1.jpg',
    images: [
      '/images/properties/dubai/binghatti-flare/flare-exterior-1.jpg',
      '/images/properties/dubai/binghatti-flare/flare-exterior-2.jpg',
      '/images/properties/dubai/binghatti-flare/flare-exterior-3.jpg',
      '/images/properties/dubai/binghatti-flare/flare-exterior-4.jpg',
      '/images/properties/dubai/binghatti-flare/flare-exterior-5.jpg',
      '/images/properties/dubai/binghatti-flare/interior-1.jpg',
      '/images/properties/dubai/binghatti-flare/interior-2.jpg',
      '/images/properties/dubai/binghatti-flare/interior-3.jpg',
      '/images/properties/dubai/binghatti-flare/interior-4.jpg',
      '/images/properties/dubai/binghatti-flare/interior-5.jpg',
      '/images/properties/dubai/binghatti-flare/lobby-1.jpg',
      '/images/properties/dubai/binghatti-flare/lobby-2.jpg',
      '/images/properties/dubai/binghatti-flare/lobby-3.jpg',
    ],
    description: {
      en: "Binghatti Flare rises dramatically above the Dubai Canal in Business Bay, offering a striking architectural statement in one of Dubai's most connected and commercially vibrant districts. Designed by Binghatti Developers — renowned for their bold, signature façade language — Flare combines the group's signature jewel-inspired cladding with interior spaces that balance open-plan living with meticulous detail.\n\nBusiness Bay's transformation into Dubai's premier business and lifestyle destination makes Binghatti Flare a compelling investment proposition, with strong short-term rental performance and projected yields exceeding 8.5%. Tax-free income, affordable entry pricing and Dubai's investor-friendly regulatory environment complete the picture.",
      tr: 'Binghatti Flare, Dubai\'nin en dinamik ve merkezi bölgelerinden biri olan Business Bay\'de, Dubai Kanalı\'na yakın konumuyla öne çıkan seçkin bir projedir. Binghatti imzası taşıyan proje, markanın karakteristik cephe tasarımını; açık planlı yaşam alanları ve özenle kurgulanmış iç mekân detaylarıyla bir araya getirir.\n\nBusiness Bay\'in Dubai\'nin önde gelen iş ve yaşam merkezlerinden biri haline gelmesi, bölgedeki kısa dönem kiralama talebini güçlendirirken; proje yatırımcılar için yüksek kira potansiyeli sunmaktadır. Vergi avantajları, rekabetçi giriş seviyeleri ve yatırımcı dostu düzenleyici yapı ile Binghatti Flare, hem gelir hem de uzun vadeli değer artışı açısından dikkat çekici bir fırsat sunar.',
    },
    highlights: {
      en: [
        'Panoramic Dubai Canal and skyline views',
        '8.5%+ projected rental yield — tax-free income',
        'Binghatti\'s signature jewel-inspired architecture',
        'Business Bay — Dubai\'s prime business district',
        'Direct Dubai Metro access nearby',
        'Affordable entry from $380,000',
      ],
      tr: [
        'Dubai Kanalı ve şehir silüetine uzanan panoramik manzaralar',
        'Güçlü kira potansiyeli ve vergi avantajlı gelir yapısı',
        'Binghatti imzasını taşıyan özgün mimari tasarım',
        'Business Bay\'de, Dubai\'nin önde gelen iş ve yaşam merkezlerinden birinde konum',
        'Metro bağlantılarına yakın, yüksek ulaşım kolaylığı',
        'Rekabetçi başlangıç seviyeleriyle erişilebilir yatırım fırsatı',
      ],
    },
    amenities: ['Infinity Pool', 'Rooftop Gym', 'Kids Pool', 'BBQ Area', 'Smart Home', 'Dedicated Parking'],
  },
  {
    slug: 'the-alba',
    name: 'The Alba',
    developer: 'Omniyat',
    location: 'Palm Jumeirah, Dubai',
    fullAddress: 'Palm Jumeirah, Dubai, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$1,200,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    completion: 'Q3 2026',
    beds: '2–4 Bed',
    floors: '12',
    totalUnits: '80',
    lat: 25.1124,
    lng: 55.139,
    heroImage: '/images/properties/dubai/the-alba/main.jpg',
    images: [
      '/images/properties/dubai/the-alba/main.jpg',
      '/images/properties/dubai/the-alba/10seatertable.webp',
      '/images/properties/dubai/the-alba/2.webp',
      '/images/properties/dubai/the-alba/3.webp',
      '/images/properties/dubai/the-alba/asset2.webp',
      '/images/properties/dubai/the-alba/asset4.webp',
      '/images/properties/dubai/the-alba/asset6.webp',
      '/images/properties/dubai/the-alba/balcony.jpg',
      '/images/properties/dubai/the-alba/beach-view.jpg',
      '/images/properties/dubai/the-alba/beach.jpg',
      '/images/properties/dubai/the-alba/bedroom.jpg',
      '/images/properties/dubai/the-alba/bedroom1.jpg',
      '/images/properties/dubai/the-alba/bird-view.jpg',
      '/images/properties/dubai/the-alba/birdview.jpg',
      '/images/properties/dubai/the-alba/dressing-room.jpg',
      '/images/properties/dubai/the-alba/entrance.jpg',
      '/images/properties/dubai/the-alba/entrance1.jpg',
      '/images/properties/dubai/the-alba/from-street.jpg',
      '/images/properties/dubai/the-alba/garden.jpg',
      '/images/properties/dubai/the-alba/garden2.jpg',
      '/images/properties/dubai/the-alba/kitchen.jpg',
      '/images/properties/dubai/the-alba/living-room.jpg',
      '/images/properties/dubai/the-alba/living-room1.jpg',
      '/images/properties/dubai/the-alba/living-room2.jpg',
      '/images/properties/dubai/the-alba/living-room3.jpg',
      '/images/properties/dubai/the-alba/living-room5.jpg',
      '/images/properties/dubai/the-alba/lobby.jpg',
      '/images/properties/dubai/the-alba/outside.jpg',
      '/images/properties/dubai/the-alba/picture-1.jpg',
      '/images/properties/dubai/the-alba/picture-1.png',
      '/images/properties/dubai/the-alba/picture-2.jpg',
      '/images/properties/dubai/the-alba/picture-3.jpg',
      '/images/properties/dubai/the-alba/picture-3.png',
      '/images/properties/dubai/the-alba/picture-4.png',
      '/images/properties/dubai/the-alba/picture-5.jpg',
      '/images/properties/dubai/the-alba/picture-6.jpg',
      '/images/properties/dubai/the-alba/picture-7.png',
      '/images/properties/dubai/the-alba/pool.jpg',
      '/images/properties/dubai/the-alba/pool1.jpg',
      '/images/properties/dubai/the-alba/pool2.jpg',
      '/images/properties/dubai/the-alba/pool3.jpg',
      '/images/properties/dubai/the-alba/viewn-from-kitchen.jpg',
    ],
    description: {
      en: "The Alba by Omniyat is an ultra-luxury residential tower on the world-famous Palm Jumeirah, offering an exceptional collection of two- to four-bedroom residences with sweeping views across the Arabian Gulf. Designed in collaboration with Dorchester Collection, The Alba represents the pinnacle of refined coastal living on Dubai's most iconic artificial island.\n\nWith just 80 residences across 12 floors, The Alba provides its residents with a distinctly private and bespoke experience: from the personalised butler and concierge services, to the private beach club and spectacular rooftop infinity pool. For investors, this ultra-prime Palm Jumeirah address commands premium rental values and exceptional long-term capital appreciation.",
      tr: 'The Alba, Omniyat tarafından Palm Jumeirah\'da hayata geçirilen, sınırlı sayıda rezidanstan oluşan seçkin bir projedir. Arap Körfezi\'ne uzanan kesintisiz manzaralarıyla öne çıkan bu koleksiyon, Dorchester Collection iş birliğiyle tasarlanmış olup, Dubai\'de rafine kıyı yaşamının en üst seviyesini temsil eder.\n\n12 kat içerisinde yalnızca 80 rezidanstan oluşan The Alba; kişisel butler ve concierge hizmetlerinden özel plaj alanına ve çatı katındaki sonsuzluk havuzuna kadar ayrıcalıklı bir yaşam deneyimi sunar. Palm Jumeirah\'daki bu nadir konum, yatırımcılar için yüksek segment kira potansiyeli ve uzun vadede güçlü değer artışı açısından öne çıkan bir fırsat niteliğindedir.',
    },
    highlights: {
      en: [
        'Iconic Palm Jumeirah address — supreme investment grade',
        'Only 80 residences — ultra-exclusive boutique development',
        'Dorchester Collection branded services',
        'Private beach club and rooftop infinity pool',
        '7.2% projected yield with strong capital appreciation',
        'Arabian Gulf and Dubai skyline panoramas',
      ],
      tr: [
        'İkonik Palm Jumeirah adresi, Dubai\'nin en prestijli yatırım bölgesinde seçkin bir konum',
        'Yalnızca 80 residence, ultra butik, sınırlı sayıda özel yaşam alanı',
        'Dorchester Collection markalı hizmetler, dünya standartlarında yönetilen ayrıcalıklı yaşam deneyimi',
        'Özel plaj kulübü ve çatı katında sonsuzluk havuzu, rafine ve seçkin sosyal alanlar',
        'Güçlü sermaye artışı potansiyeli, hedeflenen %7,2 yatırım getirisi',
        'Arap Körfezi ve Dubai silüeti panoramaları, benzersiz manzara ayrıcalığı',
      ],
    },
    amenities: ['Private Beach Club', 'Infinity Pool', 'Butler Service', 'Spa & Wellness', 'Private Cinema', 'Valet Parking'],
  },
  {
    slug: 'binghatti-aquarise',
    name: 'Binghatti Aquarise',
    developer: 'Binghatti',
    location: 'Al Jaddaf, Dubai',
    fullAddress: 'Al Jaddaf, Dubai, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$290,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    completion: 'Q2 2027',
    beds: 'Studio–2 Bed',
    floors: '32',
    totalUnits: '302',
    lat: 25.2183,
    lng: 55.3367,
    heroImage: '/images/properties/dubai/binghatti-aquarise/aquarise-exterior-1.jpg',
    images: [
      '/images/properties/dubai/binghatti-aquarise/aquarise-exterior-1.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-bedroom-1.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-bedroom-2.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-bedroom-3.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-exterior-10.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-exterior-2.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-exterior-3.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-exterior-4.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-exterior-5.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-exterior-6.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-exterior-7.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-exterior-8.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-exterior-9.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-living-room-1.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-living-room-2.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-living-room-3.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-lobby-1.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-lobby-2.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-lobby-3.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-studio-1.jpg',
      '/images/properties/dubai/binghatti-aquarise/aquarise-studio-2.jpg',
    ],
    description: {
      en: "Binghatti Aquarise is a landmark new development in the emerging Al Jaddaf waterfront district, offering studio to two-bedroom apartments at an accessible entry point that unlocks one of the highest rental yields in Dubai. The tower's flowing water-inspired architecture echoes the adjacent Dubai Creek and sets a new visual benchmark for the neighbourhood.\n\nAl Jaddaf's growing status as a cultural, hospitality and residential hub — anchored by the Dubai Culture Village, Jameel Arts Centre and a cluster of five-star hotels — drives consistently strong tenant demand. With projected yields of 9% and an affordable starting price of $290,000, Binghatti Aquarise represents outstanding value for investors seeking high-return Dubai exposure.",
      tr: 'Binghatti Aquarise, gelişen Al Jaddaf sahil bölgesinde Dubai\'de en yüksek kira getirilerinden birini sunan erişilebilir bir giriş noktasında stüdyo ve iki yatak odalı daire seçenekleri sunan önemli bir yeni projedir. Kulenin akıcı su esinli mimarisi, bitişik Dubai Creek\'i yansıtarak bölge için yeni bir görsel standart oluşturur.\n\nDubai Kültür Köyü, Jameel Arts Centre ve bir dizi beş yıldızlı otel ile desteklenen Al Jaddaf\'ın kültürel, ağırlama ve konut merkezi olarak yükselen konumu, sürekli güçlü kiracı talebi sağlar. %9 beklenen getiri ve 290.000$ seviyesindeki erişilebilir başlangıç fiyatıyla Binghatti Aquarise, Dubai\'de yüksek getirili gayrimenkul yatırımı arayan yatırımcılar için güçlü bir değer önerisi sunar.',
    },
    highlights: {
      en: [
        '9.0% projected rental yield — among Dubai\'s highest',
        'Accessible entry from $290,000',
        'Al Jaddaf Cultural District — emerging premium hub',
        'Water-inspired architecture overlooking Dubai Creek',
        'Close to Jameel Arts Centre and five-star hotels',
        'Off-plan flexible payment plans available',
      ],
      tr: [
        'Dubai\'nin en güçlü kira getirisi segmentlerinden biri, %9,0 beklenen kira getirisi',
        '290.000$\'dan başlayan erişilebilir giriş seviyesi',
        'Al Jaddaf Kültür Bölgesi, gelişen premium yaşam ve yatırım merkezi',
        'Dubai Çayı\'na bakan su esinli mimari tasarım',
        'Jameel Arts Centre ve beş yıldızlı otellere yakın ayrıcalıklı konum',
        'Plan aşamasında esnek ödeme planı seçenekleri',
      ],
    },
    amenities: ['Infinity Pool', 'Gym & Fitness', 'Kids Play Area', 'Smart Home', 'Retail Podium', 'Visitor Parking'],
  },
  {
    slug: 'mercedes-benz-places',
    name: 'Mercedes-Benz Places',
    developer: 'Binghatti',
    location: 'Downtown Dubai',
    fullAddress: 'Downtown Dubai, Dubai, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$750,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    completion: 'Q4 2027',
    beds: '1–3 Bed',
    floors: '65',
    totalUnits: '150',
    lat: 25.1972,
    lng: 55.2744,
    heroImage: '/images/properties/dubai/mercedes-benz-places/25006-aerialnight-shot-final-full.jpg',
    images: [
      '/images/properties/dubai/mercedes-benz-places/25006-aerialnight-shot-final-full.jpg',
      '/images/properties/dubai/mercedes-benz-places/25006-aerial-shot-2.jpg',
      '/images/properties/dubai/mercedes-benz-places/25006-aerial-shot-fog-logo.jpg',
      '/images/properties/dubai/mercedes-benz-places/25006-aerial-shottttt-fog.jpg',
      '/images/properties/dubai/mercedes-benz-places/25006-aerial-shotttttt.jpg',
      '/images/properties/dubai/mercedes-benz-places/25006-aerialnight-shot-final.jpg',
      '/images/properties/dubai/mercedes-benz-places/25006-bird-back.jpg',
      '/images/properties/dubai/mercedes-benz-places/25006-blue-semi-bird.jpg',
      '/images/properties/dubai/mercedes-benz-places/25006-street-shot.jpg',
      '/images/properties/dubai/mercedes-benz-places/250850-binghatti-mastercommunity-view05-halfres.jpg',
      '/images/properties/dubai/mercedes-benz-places/250850-binghatti-mastercommunity-view06-halfres.jpg',
      '/images/properties/dubai/mercedes-benz-places/250850-binghatti-mastercommunity-view06.jpg',
      '/images/properties/dubai/mercedes-benz-places/250850-binghatti-mastercommunity-view07-halfres.jpg',
      '/images/properties/dubai/mercedes-benz-places/250850-binghatti-mastercommunity-view07.jpg',
      '/images/properties/dubai/mercedes-benz-places/250850-binghatti-mastercommunity-view08-halfres.jpg',
      '/images/properties/dubai/mercedes-benz-places/250850-binghatti-mastercommunity-view08.jpg',
      '/images/properties/dubai/mercedes-benz-places/250850-binghatti-mastercommunity-view09-halfres.jpg',
      '/images/properties/dubai/mercedes-benz-places/250850-binghatti-mastercommunity-view09.jpg',
      '/images/properties/dubai/mercedes-benz-places/250850-binghatti-mastercommunity-view10-halfres.jpg',
      '/images/properties/dubai/mercedes-benz-places/250850-binghatti-mastercommunity-view10.jpg',
      '/images/properties/dubai/mercedes-benz-places/bedroom-cam01.jpg',
      '/images/properties/dubai/mercedes-benz-places/cam08-14.jpg',
      '/images/properties/dubai/mercedes-benz-places/kitchen-p1-001-post-01.jpg',
      '/images/properties/dubai/mercedes-benz-places/kitchen-p1-001-post-02.jpg',
      '/images/properties/dubai/mercedes-benz-places/kitchen-p1-001.jpg',
      '/images/properties/dubai/mercedes-benz-places/kitchen-p1-002-post-01.jpg',
      '/images/properties/dubai/mercedes-benz-places/kitchen-p1-002-post-copy00.jpg',
      '/images/properties/dubai/mercedes-benz-places/kitchen-p1-002-post0.jpg',
      '/images/properties/dubai/mercedes-benz-places/kitchen-p1-002.jpg',
      '/images/properties/dubai/mercedes-benz-places/kitchen-p1-003.jpg',
      '/images/properties/dubai/mercedes-benz-places/living-cam01-day-jpeg.jpg',
      '/images/properties/dubai/mercedes-benz-places/living-cam01-night-jpeg.jpg',
      '/images/properties/dubai/mercedes-benz-places/living-cam03-day-jpeg-rev-02.jpg',
      '/images/properties/dubai/mercedes-benz-places/living-cam03-night-jpeg-rev-02.jpg',
      '/images/properties/dubai/mercedes-benz-places/lobby-day-rev02-01-jpeg.jpg',
      '/images/properties/dubai/mercedes-benz-places/lobby-dusk-rev02-01-jpeg.jpg',
      '/images/properties/dubai/mercedes-benz-places/parking-01.2-copy.jpg',
      '/images/properties/dubai/mercedes-benz-places/parking-02.2-copy.jpg',
      '/images/properties/dubai/mercedes-benz-places/parking-02.3-copy.jpg',
      '/images/properties/dubai/mercedes-benz-places/parking-04-copy.jpg',
      '/images/properties/dubai/mercedes-benz-places/parking-06-copy.jpg',
    ],
    description: {
      en: "Mercedes-Benz Places is a globally unprecedented collaboration between Binghatti Developers and the iconic automotive brand Mercedes-Benz, bringing the brand's signature design philosophy — precision, engineering excellence, and timeless elegance — into a 65-storey supertall residential tower in the heart of Downtown Dubai.\n\nSituated within minutes of the Burj Khalifa, Dubai Mall and the Dubai Fountain, this landmark address commands the most prestigious postcode in the emirate. Each residence is designed with Mercedes-Benz's distinctive aesthetic sensibility, incorporating bespoke materials, precision engineering and a level of interior craftsmanship that transcends conventional luxury residential offerings.",
      tr: 'Mercedes-Benz Places, Binghatti Developers ile ikonik otomotiv markası Mercedes-Benz arasında eşi benzeri olmayan küresel bir iş birliğidir ve markanın imza tasarım felsefesini, hassasiyet, mühendislik mükemmeliyeti ve zamansız zarafeti Downtown Dubai\'nin kalbinde yer alan 65 katlı süper yüksek bir konut kulesine taşır.\n\nBurj Khalifa, Dubai Mall ve Dubai Fountain\'a dakikalar uzaklıkta konumlanan proje, emirliğin en prestijli posta kodunda ayrıcalıklı bir yaşam sunar. Her residence, Mercedes-Benz\'in özgün tasarım diliyle şekillendirilmiş olup, seçkin malzemeler, kusursuz mühendislik ve geleneksel lüks konut anlayışının ötesine geçen yüksek seviyede iç mekân işçiliği ile öne çıkar.',
    },
    highlights: {
      en: [
        'World-first Mercedes-Benz branded luxury residences',
        '65-storey supertall — iconic Downtown Dubai address',
        'Walking distance to Burj Khalifa and Dubai Mall',
        '7.5% projected rental yield — strong short-let demand',
        'Bespoke Mercedes-Benz interior design and materials',
        'Global investor appeal and excellent resale prospects',
      ],
      tr: [
        'Dünyanın ilk Mercedes-Benz markalı lüks konutları, ikonik bir marka iş birliğiyle şekillenen benzersiz bir yaşam ve yatırım projesi',
        '65 katlı süper yüksek, Downtown Dubai\'nin kalbinde prestijli bir adres',
        'Burj Khalifa ve Dubai Mall\'a yürüyüş mesafesinde ayrıcalıklı konum',
        'Güçlü kısa süreli kiralama talebi ile %7,5 beklenen getiri potansiyeli',
        'Özel Mercedes-Benz iç tasarım dili ve seçkin malzeme kullanımı',
        'Küresel yatırımcı ilgisi ve güçlü yeniden satış potansiyeli',
      ],
    },
    amenities: ['Supercar Valet', 'Infinity Pool', 'Private Spa', 'Sky Lounge', 'Branded Gym', 'Concierge'],
  },
  {
    slug: 'belgrove-residences',
    name: 'Belgrove Residences',
    developer: 'Ellington',
    location: 'JVC, Dubai',
    fullAddress: 'Jumeirah Village Circle, Dubai, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$350,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    completion: 'Q1 2027',
    beds: '1–2 Bed',
    floors: '20',
    totalUnits: '185',
    lat: 25.0498,
    lng: 55.2073,
    heroImage: '/images/properties/dubai/belgrove-residences/belgravia-gardens-aerial-view.jpg',
    images: [
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-aerial-view.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-beach-pool-view.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-cinema-room.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-clubhouse.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-co-working-hub.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-ellington-belgravia-gardens-clubhouse.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-fitness-studio.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-game-station-room.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-kids-play-area.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-kitchen.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-lazy-river.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-leisure-pool.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-living-and-dining.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-lobby.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-main-entrance.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-majlis.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-master-bedroom.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-private-dining.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-river-bridge.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-street-view-2.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-street-view.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-view-from-entrance.jpg',
      '/images/properties/dubai/belgrove-residences/belgravia-gardens-view-from-urban-beach.jpg',
    ],
    description: {
      en: "Belgrove Residences by Ellington Properties brings a touch of art-inspired luxury to Jumeirah Village Circle (JVC), one of Dubai's most popular and rapidly growing residential communities. Ellington is renowned for infusing each development with carefully curated art installations and design-led spaces that elevate everyday living.\n\nWith competitively priced one- and two-bedroom apartments from $350,000, Belgrove Residences offers an exceptional buy-to-let entry point into the Dubai market, targeting a rental audience of young professionals and expat families drawn to JVC's vibrant community feel, extensive parklands and excellent transport connections to both Dubai Marina and the city centre.",
      tr: 'Ellington Properties\'ın Belgrove Residences projesi, Dubai\'nin en popüler ve hızla büyüyen konut topluluklarından biri olan Jumeirah Village Circle (JVC) bölgesine sanat esinli bir lüks yaklaşım kazandıran seçkin bir projedir. Ellington, her projede günlük yaşamı yükselten özenle seçilmiş sanat enstalasyonları ve tasarım odaklı mekânlarıyla tanınır.\n\n350.000$\'dan başlayan rekabetçi fiyatlı bir ve iki yatak odalı daire seçenekleriyle Belgrove Residences, Dubai gayrimenkul piyasasına güçlü bir satın al-kirala giriş noktası sunar. JVC\'nin canlı topluluk yapısı, geniş park alanları ve Dubai Marina ile şehir merkezine sağladığı güçlü ulaşım bağlantıları, genç profesyoneller ve expat ailelerden oluşan istikrarlı bir kiracı profiline hitap eder.',
    },
    highlights: {
      en: [
        '8.2% projected rental yield — strong JVC demand',
        'Art-infused interiors by Ellington Properties',
        'Accessible entry from $350,000',
        'JVC — family-friendly community with parks and retail',
        'Close to Dubai Marina, JLT and Expo City',
        'Flexible post-handover payment plans',
      ],
      tr: [
        'Güçlü JVC talebiyle %8,2 beklenen kira getirisi',
        'Ellington Properties imzalı sanat esinli iç mekan tasarımları',
        '350.000$\'dan başlayan erişilebilir giriş seviyesi',
        'JVC, park alanları ve perakende seçenekleriyle aile dostu bir topluluk',
        'Dubai Marina, JLT ve Expo City\'ye kolay erişim',
        'Esnek teslim sonrası ödeme planı seçenekleri',
      ],
    },
    amenities: ['Art Gallery Lobby', 'Pool & Cabanas', 'Gym', 'Kids Club', 'BBQ Terrace', 'Coworking Space'],
  },
  {
    slug: 'solaya',
    name: 'Solaya',
    developer: 'Meraas',
    location: 'Jumeirah, Dubai',
    fullAddress: 'Jumeirah, Dubai, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$950,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    completion: 'Q2 2027',
    beds: '2–4 Bed',
    floors: '20',
    totalUnits: '230',
    lat: 25.2226,
    lng: 55.2456,
    heroImage: '/images/properties/dubai/solaya/picture-1.jpg',
    images: [
      '/images/properties/dubai/solaya/picture-1.jpg',
      '/images/properties/dubai/solaya/3-bedroom-garden-living-room-.jpg',
      '/images/properties/dubai/solaya/3-bedroom-garden-private-pool-.jpg',
      '/images/properties/dubai/solaya/3-bedroom-garden-terrace-.jpg',
      '/images/properties/dubai/solaya/4-bedroom-duplex-entrance-lobby-.jpg',
      '/images/properties/dubai/solaya/4-bedroom-duplex-living-room-.jpg',
      '/images/properties/dubai/solaya/4-bedroom-duplex-study-.jpg',
      '/images/properties/dubai/solaya/4-bedroom-duplex-terrace-.jpg',
      '/images/properties/dubai/solaya/5-bedroom-family-room-.jpg',
      '/images/properties/dubai/solaya/5-bedroom-kitchen-dining-.jpg',
      '/images/properties/dubai/solaya/penthouse-gym-.jpg',
      '/images/properties/dubai/solaya/penthouse-kitchen-dining-.jpg',
      '/images/properties/dubai/solaya/penthouse-living-room-.jpg',
      '/images/properties/dubai/solaya/penthouse-master-bedroom-.jpg',
      '/images/properties/dubai/solaya/penthouse-master-bedroom-ensuite-.jpg',
      '/images/properties/dubai/solaya/penthouse-private-cinema-.jpg',
      '/images/properties/dubai/solaya/penthouse-terrace-.jpg',
      '/images/properties/dubai/solaya/picture-14.jpg',
      '/images/properties/dubai/solaya/picture-15.jpg',
      '/images/properties/dubai/solaya/picture-2.jpg',
      '/images/properties/dubai/solaya/picture-3.jpg',
      '/images/properties/dubai/solaya/picture-4.jpg',
      '/images/properties/dubai/solaya/picture-5.jpg',
      '/images/properties/dubai/solaya/picture-6.jpg',
      '/images/properties/dubai/solaya/picture-7.jpg',
      '/images/properties/dubai/solaya/picture-8.jpg',
      '/images/properties/dubai/solaya/picture-9.jpg',
      '/images/properties/dubai/solaya/site-plan.jpg',
      '/images/properties/dubai/solaya/solaya-3-bedrrom-bedroom.jpg',
      '/images/properties/dubai/solaya/solaya-4-bedroom-entrance-lobby.jpg',
      '/images/properties/dubai/solaya/solaya-4-bedroom-kitchen-.jpg',
      '/images/properties/dubai/solaya/solaya-4-bedroom-kitchen-dining-room-.jpg',
      '/images/properties/dubai/solaya/solaya-4-bedroom-living-room-.jpg',
      '/images/properties/dubai/solaya/solaya-4-bedroom-master-bedroom-.jpg',
      '/images/properties/dubai/solaya/solaya-4-bedroom-master-ensuite-.jpg',
      '/images/properties/dubai/solaya/solaya-4-bedroom-master-walk-in-.jpg',
      '/images/properties/dubai/solaya/solaya-4-bedroom-secondary-suite-walk-in-.jpg',
      '/images/properties/dubai/solaya/solaya-5-bedroom-living-room-.jpg',
      '/images/properties/dubai/solaya/solaya-cinema-room.jpg',
      '/images/properties/dubai/solaya/solaya-living-room.png',
      '/images/properties/dubai/solaya/solaya-meeting-room.jpg',
      '/images/properties/dubai/solaya/solaya-private-lobby.jpg',
      '/images/properties/dubai/solaya/solaya-residence-lounge.jpg',
      '/images/properties/dubai/solaya/treatment-room.jpg',
    ],
    description: {
      en: "Solaya by Meraas is a refined residential development in Jumeirah, one of Dubai's most prestigious and sought-after beachfront communities. Developed by Meraas — the master developer behind City Walk, Bluewaters and La Mer — Solaya brings together elegant architecture, bespoke living spaces and seamless access to Dubai's best lifestyle amenities.\n\nResidents of Solaya enjoy proximity to Jumeirah's acclaimed beach clubs, fine-dining scene and boutique retail, alongside effortless connectivity to Downtown Dubai and Dubai Marina via Sheikh Zayed Road. The combination of a prime Jumeirah location, Meraas's uncompromising quality standards and a 6.8% projected yield makes Solaya a compelling proposition for discerning investors.",
      tr: 'Meraas\'ın Solaya projesi, Dubai\'nin en prestijli sahil topluluklarından biri olan Jumeirah\'ta konumlanan rafine bir konut projesidir. City Walk, Bluewaters ve La Mer gibi ikonik projelerin geliştiricisi Meraas tarafından hayata geçirilen Solaya, zarif mimariyi, özel yaşam alanlarını ve Dubai\'nin seçkin yaşam tarzı olanaklarına kesintisiz erişimi bir araya getirir.\n\nSolaya sakinleri, Jumeirah\'ın önde gelen plaj kulüplerine, seçkin yeme içme mekânlarına ve butik perakende seçeneklerine yakınlığın yanı sıra Sheikh Zayed Road üzerinden Downtown Dubai ve Dubai Marina\'ya kolay bağlantı imkânına sahiptir. Birinci sınıf Jumeirah konumu, Meraas\'ın yüksek kalite standardı ve %6,8 beklenen getiri ile Solaya, dengeli ve seçici yatırımcılar için güçlü bir yatırım önerisi sunar.',
    },
    highlights: {
      en: [
        'Prestigious Jumeirah beachfront neighbourhood',
        '6.8% projected yield in prime Meraas community',
        'Walking distance to La Mer and Jumeirah Beach',
        'Meraas master developer — City Walk, Bluewaters',
        'Effortless access to Sheikh Zayed Road',
        'Strong long-term capital appreciation in Jumeirah',
      ],
      tr: [
        'Prestijli Jumeirah sahil semti',
        'Birinci sınıf Meraas topluluğunda %6,8 beklenen getiri',
        'La Mer ve Jumeirah Plajı\'na yürüyüş mesafesinde ayrıcalıklı konum',
        'Meraas baş geliştirici, City Walk ve Bluewaters projeleriyle güçlü marka değeri',
        'Sheikh Zayed Road\'a zahmetsiz erişim',
        'Jumeirah bölgesinde güçlü uzun vadeli sermaye değer artışı potansiyeli',
      ],
    },
    amenities: ['Beach Access', 'Infinity Pool', 'Spa & Yoga', 'Fine Dining', 'Private Garden', 'Valet Parking'],
  },
  {
    slug: 'one-river-point',
    name: 'One River Point',
    developer: 'Ellington',
    location: 'Business Bay, Dubai',
    fullAddress: 'Business Bay, Dubai, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$620,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    completion: 'Q4 2027',
    beds: '1–3 Bed',
    floors: '42',
    totalUnits: '275',
    lat: 25.179,
    lng: 55.258,
    heroImage: '/images/properties/dubai/one-river-point/one-river-point-hero-shot.jpg',
    images: [
      '/images/properties/dubai/one-river-point/one-river-point-hero-shot.jpg',
      '/images/properties/dubai/one-river-point/one-river-point-aerial-view.jpg',
      '/images/properties/dubai/one-river-point/one-river-point-club-house.jpg',
      '/images/properties/dubai/one-river-point/one-river-point-facade-roof.jpg',
      '/images/properties/dubai/one-river-point/one-river-point-fitness-studio.jpg',
      '/images/properties/dubai/one-river-point/one-river-point-lobby-lounge-.jpg',
      '/images/properties/dubai/one-river-point/one-river-point-lobby-reception.jpg',
      '/images/properties/dubai/one-river-point/one-river-point-pool.jpg',
      '/images/properties/dubai/one-river-point/one-river-point-view-canal-side.jpg',
      '/images/properties/dubai/one-river-point/one-river-point-yoga.jpg',
    ],
    description: {
      en: "One River Point by Ellington Properties is a standout address in Business Bay, occupying a prized position directly on the Dubai Canal waterfront. This 42-storey tower offers one to three-bedroom apartments with spectacular unobstructed views along the canal towards Downtown Dubai, the Business Bay skyline and beyond.\n\nEllington's hallmark art-centric design philosophy is evident throughout One River Point: from curated art installations in the lobbies and common areas to carefully considered spatial planning within each residence. Business Bay's position as Dubai's fastest-growing submarket, combined with the development's canal frontage and Ellington's brand premium, drives consistent demand from high-quality tenants and international buyers.",
      tr: 'Ellington Properties\'ın One River Point projesi, doğrudan Dubai Kanalı sahil şeridinde yer alan Business Bay\'in en değerli adreslerinden birinde konumlanan seçkin bir projedir. 42 katlı bu kule, kanal, Downtown Dubai ve Business Bay silüetine uzanan etkileyici açık manzaralar sunan bir ila üç yatak odalı daire seçenekleriyle öne çıkar.\n\nEllington\'ın imzası haline gelen sanat odaklı tasarım yaklaşımı One River Point\'te güçlü şekilde hissedilir; lobi ve ortak alanlarda küratörlüğü yapılmış sanat enstalasyonları ile her residence\'ta özenle planlanmış mekân kurgusu bir araya gelir. Business Bay\'in Dubai\'nin en hızlı değer kazanan alt pazarlarından biri olması, kanal cepheli konum ve Ellington marka primiyle birleşerek yüksek kaliteli kiracı talebi ve uluslararası yatırımcı ilgisini sürekli kılar.',
    },
    highlights: {
      en: [
        'Direct Dubai Canal waterfront position',
        '7.8% projected yield in Business Bay\'s hot submarket',
        'Ellington art-centric interiors and finishes',
        'Views to Burj Khalifa and Downtown Dubai',
        '42 floors of canal-facing residences',
        'Flexible payment plan with low deposit',
      ],
      tr: [
        'Doğrudan Dubai Kanalı sahil konumu',
        'Business Bay\'in hızlı değer kazanan alt pazarında %7,8 beklenen getiri',
        'Ellington sanat merkezli iç mekan tasarımları ve seçkin bitiş malzemeleri',
        'Burj Khalifa ve Downtown Dubai\'ye uzanan panoramik manzaralar',
        'Kanal cepheli 42 katlı residence konsepti',
        'Düşük depozito ile esnek ödeme planı seçenekleri',
      ],
    },
    amenities: ['Canal Views', 'Infinity Pool', 'Art Gallery', 'Gym & Spa', 'Paddle Courts', 'Sky Deck'],
  },
  {
    slug: 'cala-del-mar',
    name: 'Cala Del Mar',
    developer: 'Ellington',
    location: 'Marjan Island, Ras Al Khaimah',
    fullAddress: 'Al Marjan Island, Ras Al Khaimah, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$474,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    completion: 'Q2 2027',
    beds: '1–4 Bed',
    floors: '25',
    totalUnits: '292',
    lat: 25.6786,
    lng: 55.9428,
    heroImage: '/images/properties/dubai/cala-del-mar/cala-del-mar-hero-shot.jpg',
    images: [
      '/images/properties/dubai/cala-del-mar/cala-del-mar-hero-shot.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-balcony-view.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-bathroom.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-bedroom-2.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-bedroom.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-clubhousejpg.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-entrance.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-exterior.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-fitness-studio.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-kids-play-area.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-kitchen.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-living-and-dining.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-living-area.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-lobbby.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-outdoor-deck.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-pool-deck.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-powder-room.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-sunken-seating.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-upper-facade.jpg',
      '/images/properties/dubai/cala-del-mar/cala-del-mar-virtual-pt-and-rowing-zone.jpg',
    ],
    description: {
      en: "Cala Del Mar by Ellington Properties is one of the most anticipated waterfront developments in the UAE, set on the spectacular Al Marjan Island in Ras Al Khaimah — the region's fastest-growing emirate, soon to be home to the first integrated resort and casino in the Middle East.\n\nInspired by Mediterranean coastal living, Cala Del Mar offers generously proportioned one- to four-bedroom residences, each designed to maximise panoramic sea views through expansive floor-to-ceiling glazing and wide, sun-drenched terraces. Residents enjoy an exclusive private boardwalk, direct beach access and a comprehensive suite of resort-grade amenities, all within a community shaped by Ellington's signature attention to art, light and lived-in luxury.",
      tr: 'Ellington Properties\'ın Cala Del Mar projesi, Orta Doğu\'nun ilk entegre tatil köyü ve eğlence destinasyonuna ev sahipliği yapması beklenen Ras Al Khaimah\'ın en hızlı gelişen bölgelerinden Al Marjan Adası\'nda konumlanan, BAE\'nin en çok beklenen sahil projelerinden biridir.\n\nAkdeniz sahil yaşamından ilham alan Cala Del Mar, geniş zemin tavandan tavana cam yüzeyler ve geniş güneşlenme terasları ile panoramik deniz manzarasını maksimuma çıkaracak şekilde tasarlanmış bir ila dört yatak odalı geniş residence seçenekleri sunar. Sakinler, Ellington\'ın sanat, ışık ve deneyim odaklı lüks yaklaşımıyla şekillenen özel bir topluluk içinde, sahil yürüyüş yolu, doğrudan plaj erişimi ve kapsamlı resort tarzı olanakların keyfini çıkarır.',
    },
    highlights: {
      en: [
        'Al Marjan Island — UAE\'s most exciting new destination',
        '9.0% projected yield alongside Wynn Resort (opening 2027)',
        'Mediterranean-inspired beachfront living',
        'Direct sea access and private boardwalk',
        'Ellington\'s signature art and light-filled design',
        'Entry from $474,000 — strong appreciation outlook',
      ],
      tr: [
        'Al Marjan Adası, BAE\'nin en heyecan verici yeni destinasyonlarından biri',
        'Yeni açılacak Wynn Resort (2027) yakınında %9,0 beklenen getiri potansiyeli',
        'Akdeniz esintili sahil yaşam konsepti',
        'Doğrudan deniz erişimi ve özel sahil yürüyüş yolu',
        'Ellington imzalı sanat ve ışık odaklı tasarım yaklaşımı',
        '474.000$\'dan başlayan giriş seviyesi ile güçlü değer artışı beklentisi',
      ],
    },
    amenities: ['Private Beach', 'Boardwalk', 'Infinity Pool', 'Yoga Pavilion', 'Kids Waterpark', 'Beachfront Dining'],
  },
];

export function getPropertyBySlug(slug: string): PropertyData | undefined {
  return allProperties.find((p) => p.slug === slug);
}

export function getPropertiesByCity(city: 'london' | 'dubai'): PropertyData[] {
  return allProperties.filter((p) => p.city === city);
}
