export interface PropertyData {
  slug: string;
  name: string;
  developer: string;
  location: string;
  fullAddress: string;
  region: 'UK' | 'UAE';
  city: 'london' | 'dubai';
  price: string;
  priceNote: { en: string; tr: string };
  yield: string;
  completion: string;
  beds: string;
  floors?: string;
  totalUnits?: string;
  lat: number;
  lng: number;
  heroImage: string;
  images: string[];
  description: { en: string; tr: string };
  highlights: { en: string[]; tr: string[] };
  amenities: string[];
}

export const allProperties: PropertyData[] = [
  // ──────────────────────── LONDON ────────────────────────
  {
    slug: 'westminster-tower',
    name: 'Westminster Tower',
    developer: 'London Square',
    location: 'SE1 7SP, London',
    fullAddress: '3 Albert Embankment, London SE1 7SP, UK',
    region: 'UK',
    city: 'london',
    price: '£550,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    yield: '5.2%',
    completion: 'Q2 2026',
    beds: '1–3 Bed',
    floors: '30',
    totalUnits: '218',
    lat: 51.4988,
    lng: -0.0988,
    heroImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1600',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=900',
      'https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?q=80&w=900',
      'https://images.unsplash.com/photo-1600607687644-c7f34b5063c8?q=80&w=900',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?q=80&w=900',
    ],
    description: {
      en: 'Westminster Tower is a prestigious riverside development on the iconic Albert Embankment in London SE1, offering spectacular views of the River Thames and the Houses of Parliament. Designed by London Square, this 30-storey landmark combines contemporary architecture with premium finishes to deliver an unrivalled urban living experience in the heart of the capital.\n\nResidents benefit from a prime Zone 1 location with effortless access to Westminster, Waterloo, Vauxhall and the City, making it an ideal choice for both owner-occupiers and investors seeking strong rental demand and long-term capital growth.',
      tr: 'Westminster Tower, Londra SE1\'deki ikonik Albert Embankment üzerinde prestijli bir nehir kenarı projesidir. Temiz Parlamento ve Thames kıyısı manzaralarını sunan bu 30 katlı yapı, London Square tarafından tasarlanmış olup modern mimariyi premium iç mekan detaylarıyla buluşturuyor.\n\nSakinler, Westminster, Waterloo, Vauxhall ve City\'ye kolay erişim imkânı sunan birinci bölge konumundan yararlanır; bu da hem kendi oturmak isteyen alıcılar hem de güçlü kira talebi ve uzun vadeli değer artışı arayan yatırımcılar için ideal bir seçenek haline getiriyor.',
    },
    highlights: {
      en: [
        'Prime Zone 1 riverside location on Albert Embankment',
        'Panoramic Thames and Parliament views',
        '30 storeys with 218 luxury apartments',
        '24-hour concierge and security',
        'Moments from Vauxhall and Westminster stations',
        'Strong rental yield driven by proximity to government quarter',
      ],
      tr: [
        'Albert Embankment\'te birinci bölge nehir kenarı konumu',
        'Thames ve Parlamento\'yu kucaklayan panoramik manzara',
        '218 lüks daire ile 30 katlı yapı',
        '24 saat kapıcı ve güvenlik hizmeti',
        'Vauxhall ve Westminster istasyonlarına yakınlık',
        'Hükümet bölgesine yakınlık sayesinde güçlü kira getirisi',
      ],
    },
    amenities: ['24hr Concierge', 'Residents Lounge', 'Gym & Wellness', 'Rooftop Terrace', 'Cycle Storage', 'Secure Parking'],
  },
  {
    slug: 'ransomes-wharf',
    name: "Ransome's Wharf",
    developer: 'London Square',
    location: 'SW11, London',
    fullAddress: "Ransome's Wharf, Battersea, London SW11, UK",
    region: 'UK',
    city: 'london',
    price: '£725,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    yield: '4.8%',
    completion: 'Q4 2026',
    beds: '1–3 Bed',
    floors: '12',
    totalUnits: '152',
    lat: 51.4806,
    lng: -0.1694,
    heroImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1600',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=900',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=900',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?q=80&w=900',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?q=80&w=900',
    ],
    description: {
      en: "Ransome's Wharf is an exceptional waterfront development set along the banks of the River Thames in Battersea, SW11. Designed by London Square, this boutique collection of 152 apartments delivers refined contemporary living in one of London's most sought-after neighbourhoods.\n\nFrom generous private balconies and terraces overlooking the river, to refined interiors crafted with the finest materials, every detail at Ransome's Wharf has been meticulously considered. Residents enjoy direct access to the vibrant South Bank, Chelsea Bridge Wharf and the extensive green spaces of Battersea Park.",
      tr: "Ransome's Wharf, Battersea SW11'de Thames Nehri kıyısında yer alan olağanüstü bir su kenarı projesidir. London Square tarafından tasarlanan bu butik koleksiyonda 152 daire, Londra'nın en gözde semtlerinden birinde özenle hazırlanmış çağdaş bir yaşam sunuyor.\n\nNehre bakan geniş özel balkon ve teras gibi detaylardan en kaliteli malzemelerle tasarlanan iç mekânlara kadar her ayrıntı titizlikle düşünülmüş. Sakinler, canlı South Bank, Chelsea Bridge ve Battersea Parkı'nın yeşil alanlarına doğrudan erişim imkânından faydalanıyor.",
    },
    highlights: {
      en: [
        'Exclusive Thames waterfront location in Battersea',
        'Private balconies and terraces with river views',
        'Boutique development of 152 luxury apartments',
        "Walking distance to Battersea Park and King's Road",
        'Convenient access to National Rail and underground',
        'Premium specification throughout',
      ],
      tr: [
        'Battersea\'da Thames kıyısında özel konum',
        'Nehir manzaralı özel balkon ve teraslar',
        '152 lüks dairenin bulunduğu butik proje',
        'Battersea Parkı ve King\'s Road\'a yürüyüş mesafesi',
        'Banliyö treni ve metroya kolay erişim',
        'Tüm dairelerde premium teknik özellikler',
      ],
    },
    amenities: ['River Views', 'Private Balconies', 'Concierge', 'Residents Lounge', 'Cycle Storage', 'Landscaped Gardens'],
  },
  {
    slug: 'woolwich-central',
    name: 'Woolwich Central',
    developer: 'London Square',
    location: 'SE18, London',
    fullAddress: 'Woolwich, London SE18, UK',
    region: 'UK',
    city: 'london',
    price: '£380,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    yield: '5.5%',
    completion: 'Q1 2027',
    beds: '1–2 Bed',
    floors: '15',
    totalUnits: '193',
    lat: 51.4913,
    lng: 0.0672,
    heroImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1600',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=900',
      'https://images.unsplash.com/photo-1600566752547-5a418d83b4c7?q=80&w=900',
      'https://images.unsplash.com/photo-1615873968403-89e068629265?q=80&w=900',
      'https://images.unsplash.com/photo-1600573472550-8090733a21e0?q=80&w=900',
    ],
    description: {
      en: "Woolwich Central represents an outstanding investment opportunity in one of London's most rapidly regenerating areas. Located in the heart of Woolwich SE18, this development benefits from the Elizabeth Line (Crossrail) rail connection, which dramatically reduces journey times to central London and significantly increases property values.\n\nWith a target rental yield of 5.5% and entry pricing from £380,000, Woolwich Central offers excellent affordability relative to inner-London alternatives, alongside strong projected capital growth driven by ongoing regeneration investment in the Royal Borough of Greenwich.",
      tr: 'Woolwich Central, Londra\'nın en hızlı dönüşen bölgelerinden birinde olağanüstü bir yatırım fırsatı sunuyor. SE18 Woolwich\'in kalbinde yer alan bu proje, merkezi Londra\'ya seyahat sürelerini önemli ölçüde kısaltan ve gayrimenkul değerlerini kayda değer şekilde artıran Elizabeth Line (Crossrail) bağlantısından yararlanıyor.\n\n%5,5 hedef kira getirisi ve 380.000£\'dan başlayan fiyatlarıyla Woolwich Central, iç Londra alternatiflerine kıyasla mükemmel bir satın alınabilirlik seviyesi sunarken, Greenwich Kraliyet İlçesi\'ndeki süregelen kentsel dönüşüm yatırımlarıyla desteklenen güçlü sermaye büyümesi beklentisi sunuyor.',
    },
    highlights: {
      en: [
        'Direct Elizabeth Line (Crossrail) access',
        'Prices from £380,000 — strong affordability',
        '5.5% projected rental yield',
        'Part of major Woolwich regeneration programme',
        'Zone 3 — fast connections to Canary Wharf and Bond Street',
        'High rental demand from tech and finance professionals',
      ],
      tr: [
        'Doğrudan Elizabeth Line (Crossrail) erişimi',
        '380.000£\'dan başlayan fiyatlarla mükemmel erişilebilirlik',
        '%5,5 beklenen kira getirisi',
        'Büyük Woolwich yenileme programının parçası',
        '3. Bölge — Canary Wharf ve Bond Street\'e hızlı bağlantı',
        'Teknoloji ve finans profesyonellerinden yüksek kira talebi',
      ],
    },
    amenities: ['Elizabeth Line Hub', 'Residents Gym', 'Concierge', 'Roof Terrace', 'Secure Parking', 'Private Courtyard'],
  },
  {
    slug: 'prince-of-wales-drive',
    name: 'Prince Of Wales Drive',
    developer: 'Berkeley Group',
    location: 'SW11 4FA, London',
    fullAddress: 'Prince of Wales Drive, Battersea, London SW11 4FA, UK',
    region: 'UK',
    city: 'london',
    price: '£850,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    yield: '4.5%',
    completion: 'Ready to Move',
    beds: '1–3 Bed',
    floors: '18',
    totalUnits: '264',
    lat: 51.4757,
    lng: -0.1442,
    heroImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1600',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=900',
      'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?q=80&w=900',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=900',
      'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?q=80&w=900',
    ],
    description: {
      en: "Prince of Wales Drive is a landmark Berkeley Group development set opposite Battersea Park, one of London's most beloved green spaces. Perfectly positioned in SW11, one of the capital's most prestigious residential postcodes, this collection of beautifully designed apartments features generous proportions, premium specification and unparalleled access to both the park and the vibrant cultural attractions of Chelsea, Sloane Square and the King's Road.\n\nAs a ready-to-move development with strong existing rental demand, Prince of Wales Drive offers investors immediate rental income potential alongside powerful long-term capital appreciation in a blue-chip Battersea location.",
      tr: 'Prince of Wales Drive, Londra\'nın en sevilen yeşil alanlarından biri olan Battersea Parkı karşısında konumlanan önemli bir Berkeley Group projesidir. Başkentin en prestijli konut posta kodlarından biri olan SW11\'de mükemmel konumuyla bu daire koleksiyonu, geniş mekânlar, premium teknik özellikler ve hem parka hem de Chelsea, Sloane Square ve King\'s Road\'ın canlı kültürel çekiciliklerine eşsiz erişim sunuyor.\n\nGüçlü kira talebiyle hazır teslimat özelliğine sahip bu proje, yatırımcılara mavi çipli Battersea konumunda güçlü uzun vadeli sermaye kazancının yanı sıra anında kira geliri potansiyeli sunuyor.',
    },
    highlights: {
      en: [
        'Ready to move — immediate rental income potential',
        'Opposite iconic Battersea Park',
        'Blue-chip SW11 address',
        'Berkeley Group premium build quality',
        '5-minute walk to Battersea Power Station and Elizabeth Line',
        'Chelsea and South Kensington within easy reach',
      ],
      tr: [
        'Hazır teslimat — anında kira geliri potansiyeli',
        'İkonik Battersea Parkı\'nın karşısında',
        'Prestijli SW11 adresi',
        'Berkeley Group premium yapı kalitesi',
        'Battersea Power Station ve Elizabeth Line\'a 5 dakika yürüyüş',
        'Chelsea ve South Kensington\'a kolay erişim',
      ],
    },
    amenities: ['Park Views', 'Swimming Pool', 'Spa & Gym', '24hr Concierge', 'Secure Parking', 'Residents Garden'],
  },
  {
    slug: 'sterling-place',
    name: 'Sterling Place',
    developer: 'Barratt London',
    location: 'SW17 0SR, London',
    fullAddress: 'Sterling Place, Tooting, London SW17 0SR, UK',
    region: 'UK',
    city: 'london',
    price: '£420,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    yield: '5.0%',
    completion: 'Q3 2026',
    beds: 'Studio–2 Bed',
    floors: '14',
    totalUnits: '168',
    lat: 51.4256,
    lng: -0.1718,
    heroImage: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1600',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=900',
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?q=80&w=900',
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=900',
      'https://images.unsplash.com/photo-1556020685-ae41abfc9365?q=80&w=900',
    ],
    description: {
      en: "Sterling Place by Barratt London brings a new standard of contemporary urban living to the heart of Tooting, SW17. Sitting within an emerging residential hub that is attracting significant investment and regeneration, this development offers studios, one- and two-bedroom apartments that combine modern design, efficient layouts and high-quality specification.\n\nTooting's growing popularity among young professionals and families — driven by outstanding transport links including the Northern Line and National Rail, alongside an exceptional food and lifestyle scene — makes Sterling Place a compelling buy-to-let proposition with projected yields of 5%.",
      tr: 'Barratt London\'ın Sterling Place projesi, SW17 Tooting\'in kalbine çağdaş kentsel yaşamda yeni bir standart getiriyor. Önemli yatırım ve kentsel dönüşüm çeken gelişen bir konut merkezi içinde yer alan bu proje, modern tasarım, verimli planlar ve yüksek kaliteli özelliklerle stüdyo, bir ve iki yatak odalı daireler sunuyor.\n\nNorthern Line ve Millî Demiryolları dahil üstün ulaşım bağlantıları ile olağanüstü yemek ve yaşam tarzı sahnesiyle genç profesyoneller ve aileler arasında giderek popülerleşen Tooting, Sterling Place\'i %5 beklenen getiriyle cazip bir satın al-kiraya ver teklifi haline getiriyor.',
    },
    highlights: {
      en: [
        'Excellent value entry point from £420,000',
        'Northern Line direct — city in under 30 minutes',
        'Tooting market and vibrant dining scene nearby',
        "One of South London's fastest-growing submarkets",
        '5.0% projected rental yield',
        'Modern specification with private outdoor space',
      ],
      tr: [
        '420.000£\'dan başlayan mükemmel değer giriş noktası',
        'Northern Line direkt — 30 dakikada şehir merkezi',
        'Tooting pazarı ve canlı yemek sahnesi yakınında',
        'Güney Londra\'nın en hızlı büyüyen alt pazarlarından biri',
        '%5,0 beklenen kira getirisi',
        'Özel açık alan ile modern teknik özellikler',
      ],
    },
    amenities: ['Roof Terrace', 'Residents Gym', 'Bike Storage', 'Communal Gardens', 'EV Charging', 'Video Entry'],
  },
  {
    slug: 'white-city-living',
    name: 'White City Living',
    developer: 'Berkeley Group',
    location: 'W12 7RQ, London',
    fullAddress: 'Westfield Avenue, White City, London W12 7RQ, UK',
    region: 'UK',
    city: 'london',
    price: '£650,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    yield: '4.6%',
    completion: 'Ready to Move',
    beds: '1–3 Bed',
    floors: '22',
    totalUnits: '1,462',
    lat: 51.509,
    lng: -0.2332,
    heroImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=1600',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=900',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=900',
      'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?q=80&w=900',
      'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?q=80&w=900',
    ],
    description: {
      en: "White City Living is Berkeley Group's flagship mixed-use development in West London, forming the centrepiece of the £8 billion White City regeneration. Situated at the doorstep of Westfield London — the largest urban shopping centre in Europe — and adjacent to the thriving Imperial College London campus, this landmark scheme redefines the concept of urban living.\n\nWith over 1,400 homes across a series of elegant towers, comprehensive on-site amenities and direct Underground access at Wood Lane station, White City Living offers investors exceptional connectivity, long-term capital growth potential and strong rental demand driven by proximity to major employment hubs in media, tech and academia.",
      tr: 'White City Living, Batı Londra\'da 8 milyar £\'lık White City kentsel dönüşümünün merkezini oluşturan Berkeley Group\'un amiral gemisi karma kullanımlı projesidir. Avrupa\'nın en büyük kentsel alışveriş merkezi Westfield London\'ın avlusunda ve gelişen Imperial College London kampüsünün yanı başında yer alan bu önemli plan, kentsel yaşam anlayışını yeniden tanımlıyor.\n\nBirden fazla zarif kule genelinde 1.400\'den fazla konut, kapsamlı yerinde olanaklar ve Wood Lane istasyonunda doğrudan metro erişimiyle White City Living, yatırımcılara medya, teknoloji ve akademi alanlarındaki büyük iş merkezlerine yakınlık sayesinde olağanüstü bağlantı, uzun vadeli sermaye büyüme potansiyeli ve güçlü kira talebi sunuyor.',
    },
    highlights: {
      en: [
        'Heart of the £8 billion White City regeneration',
        'Next to Westfield London — Europe\'s largest urban mall',
        'Direct Circle & Hammersmith line access at Wood Lane',
        'Proximity to Imperial College London and BBC Media Village',
        "Berkeley Group's largest London development",
        'Strong long-term capital appreciation prospects',
      ],
      tr: [
        '8 milyar £\'lık White City dönüşümünün merkezi',
        'Avrupa\'nın en büyük kentsel alışveriş merkezi Westfield London\'ın yanı başında',
        'Wood Lane\'de Circle ve Hammersmith hattına doğrudan erişim',
        'Imperial College London ve BBC Media Village\'a yakınlık',
        "Berkeley Group'un Londra'daki en büyük projesi",
        'Güçlü uzun vadeli sermaye değer artışı beklentisi',
      ],
    },
    amenities: ['Swimming Pool', 'Spa & Gym', '24hr Concierge', 'Cinema Room', 'Roof Garden', 'Private Dining'],
  },

  // ──────────────────────── DUBAI ────────────────────────
  {
    slug: 'binghatti-flare',
    name: 'Binghatti Flare',
    developer: 'Binghatti',
    location: 'Business Bay, Dubai',
    fullAddress: 'Business Bay, Dubai, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$380,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    yield: '8.5%',
    completion: 'Q1 2027',
    beds: '1–3 Bed',
    floors: '35',
    totalUnits: '226',
    lat: 25.1858,
    lng: 55.2625,
    heroImage: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?q=80&w=1600',
    images: [
      'https://images.unsplash.com/photo-1518684079-3c830dcef090?q=80&w=900',
      'https://images.unsplash.com/photo-1628592102751-ba83b0314276?q=80&w=900',
      'https://images.unsplash.com/photo-1600573472550-8090733a21e0?q=80&w=900',
      'https://images.unsplash.com/photo-1611892440504-42a792e24d32?q=80&w=900',
    ],
    description: {
      en: "Binghatti Flare rises dramatically above the Dubai Canal in Business Bay, offering a striking architectural statement in one of Dubai's most connected and commercially vibrant districts. Designed by Binghatti Developers — renowned for their bold, signature façade language — Flare combines the group's signature jewel-inspired cladding with interior spaces that balance open-plan living with meticulous detail.\n\nBusiness Bay's transformation into Dubai's premier business and lifestyle destination makes Binghatti Flare a compelling investment proposition, with strong short-term rental performance and projected yields exceeding 8.5%. Tax-free income, affordable entry pricing and Dubai's investor-friendly regulatory environment complete the picture.",
      tr: 'Binghatti Flare, Dubai\'nin en bağlantılı ve ticari açıdan en canlı ilçelerinden biri olan Business Bay\'de Dubai Kanalı\'nın üzerinde dramatik bir şekilde yükseliyor. Cesur imza cephe diliyle tanınan Binghatti tarafından tasarlanan Flare, grubun imza mücevher esinli kaplamasını, açık planlı yaşamı titiz detaylarla dengeleyen iç mekânlarla buluşturuyor.\n\nBusiness Bay\'in Dubai\'nin önde gelen iş ve yaşam tarzı merkezi haline dönüşümü, güçlü kısa süreli kiralama performansı ve %8,5\'i aşan beklenen getirilerle Binghatti Flare\'i cazip bir yatırım teklifi haline getiriyor. Vergisiz gelir, erişilebilir giriş fiyatı ve Dubai\'nin yatırımcı dostu düzenleyici ortamı tabloyu tamamlıyor.',
    },
    highlights: {
      en: [
        'Panoramic Dubai Canal and skyline views',
        '8.5%+ projected rental yield — tax-free income',
        'Binghatti\'s signature jewel-inspired architecture',
        'Business Bay — Dubai\'s prime business district',
        'Direct Dubai Metro access nearby',
        'Affordable entry from $380,000',
      ],
      tr: [
        'Panoramik Dubai Kanalı ve silüet manzarası',
        'Beklenen %8,5+ kira getirisi — vergisiz gelir',
        'Binghatti imzalı mücevher esinli mimari',
        'Business Bay — Dubai\'nin önde gelen iş ilçesi',
        'Yakınında doğrudan Dubai Metro erişimi',
        '380.000$\'dan başlayan erişilebilir giriş',
      ],
    },
    amenities: ['Infinity Pool', 'Rooftop Gym', 'Kids Pool', 'BBQ Area', 'Smart Home', 'Dedicated Parking'],
  },
  {
    slug: 'the-alba',
    name: 'The Alba',
    developer: 'Omniyat',
    location: 'Palm Jumeirah, Dubai',
    fullAddress: 'Palm Jumeirah, Dubai, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$1,200,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    yield: '7.2%',
    completion: 'Q3 2026',
    beds: '2–4 Bed',
    floors: '12',
    totalUnits: '80',
    lat: 25.1124,
    lng: 55.139,
    heroImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1600',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=900',
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?q=80&w=900',
      'https://images.unsplash.com/photo-1540541338537-09cf46717399?q=80&w=900',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?q=80&w=900',
    ],
    description: {
      en: "The Alba by Omniyat is an ultra-luxury residential tower on the world-famous Palm Jumeirah, offering an exceptional collection of two- to four-bedroom residences with sweeping views across the Arabian Gulf. Designed in collaboration with Dorchester Collection, The Alba represents the pinnacle of refined coastal living on Dubai's most iconic artificial island.\n\nWith just 80 residences across 12 floors, The Alba provides its residents with a distinctly private and bespoke experience: from the personalised butler and concierge services, to the private beach club and spectacular rooftop infinity pool. For investors, this ultra-prime Palm Jumeirah address commands premium rental values and exceptional long-term capital appreciation.",
      tr: 'Omniyat\'ın The Alba projesi, dünyaca ünlü Palm Jumeirah\'da iki ila dört yatak odalı residence\'ların olağanüstü bir koleksiyonunu Arap Körfezi\'nin kesintisiz manzarasıyla birlikte sunuyor. Dorchester Collection iş birliğiyle tasarlanan The Alba, Dubai\'nin en ikonik yapay adasındaki rafine kıyı yaşamının zirvesini temsil ediyor.\n\n12 katta yalnızca 80 residence ile The Alba, sakinlerine kişisel butler ve concierge hizmetlerinden özel plaj kulübüne ve muhteşem çatı sonsuz havuzuna uzanan belirgin biçimde özel ve kişiye özel bir deneyim sunuyor. Yatırımcılar için Palm Jumeirah\'daki bu ultra-prime adres, premium kira değerleri ve olağanüstü uzun vadeli sermaye artışı sağlıyor.',
    },
    highlights: {
      en: [
        'Iconic Palm Jumeirah address — supreme investment grade',
        'Only 80 residences — ultra-exclusive boutique development',
        'Dorchester Collection branded services',
        'Private beach club and rooftop infinity pool',
        '7.2% projected yield with strong capital appreciation',
        'Arabian Gulf and Dubai skyline panoramas',
      ],
      tr: [
        'İkonik Palm Jumeirah adresi — en yüksek yatırım kategorisi',
        'Yalnızca 80 residence — ultra seçkin butik proje',
        'Dorchester Collection markalı hizmetler',
        'Özel plaj kulübü ve çatı sonsuz havuzu',
        'Güçlü sermaye artışıyla %7,2 beklenen getiri',
        'Arap Körfezi ve Dubai silüeti panoramaları',
      ],
    },
    amenities: ['Private Beach Club', 'Infinity Pool', 'Butler Service', 'Spa & Wellness', 'Private Cinema', 'Valet Parking'],
  },
  {
    slug: 'binghatti-aquarise',
    name: 'Binghatti Aquarise',
    developer: 'Binghatti',
    location: 'Al Jaddaf, Dubai',
    fullAddress: 'Al Jaddaf, Dubai, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$290,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    yield: '9.0%',
    completion: 'Q2 2027',
    beds: 'Studio–2 Bed',
    floors: '32',
    totalUnits: '302',
    lat: 25.2183,
    lng: 55.3367,
    heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1600',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=900',
      'https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?q=80&w=900',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?q=80&w=900',
      'https://images.unsplash.com/photo-1617098900591-3f90928e8c54?q=80&w=900',
    ],
    description: {
      en: "Binghatti Aquarise is a landmark new development in the emerging Al Jaddaf waterfront district, offering studio to two-bedroom apartments at an accessible entry point that unlocks one of the highest rental yields in Dubai. The tower's flowing water-inspired architecture echoes the adjacent Dubai Creek and sets a new visual benchmark for the neighbourhood.\n\nAl Jaddaf's growing status as a cultural, hospitality and residential hub — anchored by the Dubai Culture Village, Jameel Arts Centre and a cluster of five-star hotels — drives consistently strong tenant demand. With projected yields of 9% and an affordable starting price of $290,000, Binghatti Aquarise represents outstanding value for investors seeking high-return Dubai exposure.",
      tr: 'Binghatti Aquarise, gelişen Al Jaddaf sahil bölgesinde Dubai\'de en yüksek kira getirilerinden birini açan erişilebilir bir giriş noktasında stüdyo ila iki yatak odalı daireler sunan önemli bir yeni projedir. Kulenin akıcı su esinli mimarisi, bitişik Dubai Çayı\'nı yansıtıyor ve bölge için yeni bir görsel standart belirliyor.\n\nDubai Kültür Köyü, Jameel Arts Centre ve bir dizi beş yıldızlı otel tarafından desteklenen Al Jaddaf\'ın kültürel, ağırlama ve konut merkezi olarak büyüyen konumu, sürekli güçlü kiracı talebi sağlıyor. %9 beklenen getiri ve 290.000$\'lık erişilebilir başlangıç fiyatıyla Binghatti Aquarise, yüksek getirili Dubai yatırımı arayan yatırımcılar için olağanüstü bir değer sunuyor.',
    },
    highlights: {
      en: [
        '9.0% projected rental yield — among Dubai\'s highest',
        'Accessible entry from $290,000',
        'Al Jaddaf Cultural District — emerging premium hub',
        'Water-inspired architecture overlooking Dubai Creek',
        'Close to Jameel Arts Centre and five-star hotels',
        'Off-plan flexible payment plans available',
      ],
      tr: [
        'Dubai\'nin en yükseklerinden %9,0 beklenen kira getirisi',
        '290.000$\'dan başlayan erişilebilir giriş',
        'Al Jaddaf Kültür Bölgesi — gelişen premium merkez',
        'Dubai Çayı\'na bakan su esinli mimari',
        'Jameel Arts Centre ve beş yıldızlı otellere yakınlık',
        'Plan aşamasında esnek ödeme planları mevcut',
      ],
    },
    amenities: ['Infinity Pool', 'Gym & Fitness', 'Kids Play Area', 'Smart Home', 'Retail Podium', 'Visitor Parking'],
  },
  {
    slug: 'mercedes-benz-places',
    name: 'Mercedes-Benz Places',
    developer: 'Binghatti',
    location: 'Downtown Dubai',
    fullAddress: 'Downtown Dubai, Dubai, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$750,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    yield: '7.5%',
    completion: 'Q4 2027',
    beds: '1–3 Bed',
    floors: '65',
    totalUnits: '150',
    lat: 25.1972,
    lng: 55.2744,
    heroImage: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?q=80&w=1600',
    images: [
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?q=80&w=900',
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?q=80&w=900',
      'https://images.unsplash.com/photo-1617098900591-3f90928e8c54?q=80&w=900',
      'https://images.unsplash.com/photo-1628592102751-ba83b0314276?q=80&w=900',
    ],
    description: {
      en: "Mercedes-Benz Places is a globally unprecedented collaboration between Binghatti Developers and the iconic automotive brand Mercedes-Benz, bringing the brand's signature design philosophy — precision, engineering excellence, and timeless elegance — into a 65-storey supertall residential tower in the heart of Downtown Dubai.\n\nSituated within minutes of the Burj Khalifa, Dubai Mall and the Dubai Fountain, this landmark address commands the most prestigious postcode in the emirate. Each residence is designed with Mercedes-Benz's distinctive aesthetic sensibility, incorporating bespoke materials, precision engineering and a level of interior craftsmanship that transcends conventional luxury residential offerings.",
      tr: 'Mercedes-Benz Places, Binghatti Developers ile ikonik otomotiv markası Mercedes-Benz arasında eşi görülmemiş küresel bir iş birliğidir. Markanın imza tasarım felsefesini — hassasiyet, mühendislik mükemmeliyeti ve zamansız zarafet — Downtown Dubai\'nin kalbinde 65 katlı süper yüksek bir konut kulesine taşıyor.\n\nBurj Khalifa, Dubai Mall ve Dubai Çeşmesi\'ne dakikalar uzaklıkta konumlanan bu bina, emirlikteki en prestijli posta koduna sahip. Her residence, özgün malzemeleri, hassas mühendisliği ve geleneksel lüks konut tekliflerinin ötesine geçen bir iç mekan işçiliği düzeyini içeren Mercedes-Benz\'in kendine özgü estetik anlayışıyla tasarlanmıştır.',
    },
    highlights: {
      en: [
        'World-first Mercedes-Benz branded luxury residences',
        '65-storey supertall — iconic Downtown Dubai address',
        'Walking distance to Burj Khalifa and Dubai Mall',
        '7.5% projected rental yield — strong short-let demand',
        'Bespoke Mercedes-Benz interior design and materials',
        'Global investor appeal and excellent resale prospects',
      ],
      tr: [
        'Dünya\'nın ilk Mercedes-Benz markalı lüks konutları',
        '65 katlı süper yüksek — ikonik Downtown Dubai adresi',
        'Burj Khalifa ve Dubai Mall\'a yürüyüş mesafesi',
        'Güçlü kısa süreli kiralama talebiyle %7,5 beklenen getiri',
        'Özel Mercedes-Benz iç tasarım ve malzemeleri',
        'Küresel yatırımcı çekiciliği ve mükemmel yeniden satış beklentisi',
      ],
    },
    amenities: ['Supercar Valet', 'Infinity Pool', 'Private Spa', 'Sky Lounge', 'Branded Gym', 'Concierge'],
  },
  {
    slug: 'belgrove-residences',
    name: 'Belgrove Residences',
    developer: 'Ellington',
    location: 'JVC, Dubai',
    fullAddress: 'Jumeirah Village Circle, Dubai, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$350,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    yield: '8.2%',
    completion: 'Q1 2027',
    beds: '1–2 Bed',
    floors: '20',
    totalUnits: '185',
    lat: 25.0498,
    lng: 55.2073,
    heroImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1600',
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=900',
      'https://images.unsplash.com/photo-1619994571228-3f5e866f4e27?q=80&w=900',
      'https://images.unsplash.com/photo-1501183638710-841dd1904471?q=80&w=900',
      'https://images.unsplash.com/photo-1524562865630-f191ea880af5?q=80&w=900',
    ],
    description: {
      en: "Belgrove Residences by Ellington Properties brings a touch of art-inspired luxury to Jumeirah Village Circle (JVC), one of Dubai's most popular and rapidly growing residential communities. Ellington is renowned for infusing each development with carefully curated art installations and design-led spaces that elevate everyday living.\n\nWith competitively priced one- and two-bedroom apartments from $350,000, Belgrove Residences offers an exceptional buy-to-let entry point into the Dubai market, targeting a rental audience of young professionals and expat families drawn to JVC's vibrant community feel, extensive parklands and excellent transport connections to both Dubai Marina and the city centre.",
      tr: 'Ellington Properties\'ın Belgrove Residences projesi, Dubai\'nin en popüler ve hızla büyüyen konut topluluklarından biri olan Jumeirah Village Circle\'a (JVC) sanat esinli bir lüks dokunuş katıyor. Ellington, her projeyi günlük yaşamı yükselten özenle seçilmiş sanat enstalasyonları ve tasarım odaklı mekânlarla bezemeyle tanınıyor.\n\n350.000$\'dan başlayan rekabetçi fiyatlı bir ve iki yatak odalı dairelerle Belgrove Residences, Dubai pazarına olağanüstü bir satın al-kiraya ver giriş noktası sağlıyor. JVC\'nin canlı topluluk hissi, geniş parklar ve hem Dubai Marina\'ya hem de şehir merkezine mükemmel ulaşım bağlantılarına ilgi duyan genç profesyoneller ve expat ailelerden oluşan bir kira kitlesini hedefliyor.',
    },
    highlights: {
      en: [
        '8.2% projected rental yield — strong JVC demand',
        'Art-infused interiors by Ellington Properties',
        'Accessible entry from $350,000',
        'JVC — family-friendly community with parks and retail',
        'Close to Dubai Marina, JLT and Expo City',
        'Flexible post-handover payment plans',
      ],
      tr: [
        'Güçlü JVC talebiyle %8,2 beklenen kira getirisi',
        'Ellington Properties imzalı sanat esinli iç mekanlar',
        '350.000$\'dan başlayan erişilebilir giriş',
        'JVC — park ve perakende alanlarıyla aile dostu topluluk',
        'Dubai Marina, JLT ve Expo City\'ye yakınlık',
        'Esnek teslim sonrası ödeme planları',
      ],
    },
    amenities: ['Art Gallery Lobby', 'Pool & Cabanas', 'Gym', 'Kids Club', 'BBQ Terrace', 'Coworking Space'],
  },
  {
    slug: 'solaya',
    name: 'Solaya',
    developer: 'Meraas',
    location: 'Jumeirah, Dubai',
    fullAddress: 'Jumeirah, Dubai, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$950,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    yield: '6.8%',
    completion: 'Q2 2027',
    beds: '2–4 Bed',
    floors: '20',
    totalUnits: '230',
    lat: 25.2226,
    lng: 55.2456,
    heroImage: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?q=80&w=1600',
    images: [
      'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?q=80&w=900',
      'https://images.unsplash.com/photo-1540541338537-09cf46717399?q=80&w=900',
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?q=80&w=900',
      'https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?q=80&w=900',
    ],
    description: {
      en: "Solaya by Meraas is a refined residential development in Jumeirah, one of Dubai's most prestigious and sought-after beachfront communities. Developed by Meraas — the master developer behind City Walk, Bluewaters and La Mer — Solaya brings together elegant architecture, bespoke living spaces and seamless access to Dubai's best lifestyle amenities.\n\nResidents of Solaya enjoy proximity to Jumeirah's acclaimed beach clubs, fine-dining scene and boutique retail, alongside effortless connectivity to Downtown Dubai and Dubai Marina via Sheikh Zayed Road. The combination of a prime Jumeirah location, Meraas's uncompromising quality standards and a 6.8% projected yield makes Solaya a compelling proposition for discerning investors.",
      tr: 'Meraas\'ın Solaya projesi, Dubai\'nin en prestijli ve gözde sahil topluluklarından biri olan Jumeirah\'da rafine bir konut projesidir. City Walk, Bluewaters ve La Mer\'in baş geliştiricisi Meraas tarafından inşa edilen Solaya, zarif mimariyi, özel yaşam alanlarını ve Dubai\'nin en iyi yaşam tarzı olanaklarına kesintisiz erişimi bir araya getiriyor.\n\nSolaya sakinleri, Jumeirah\'ın ünlü plaj kulüplerine, birinci sınıf yeme-içme mekânlarına ve butik perakendesine yakınlığın yanı sıra Şeyh Zayed Yolu üzerinden Downtown Dubai ve Dubai Marina\'ya zahmetsiz bağlantının keyfini çıkarıyor. Birinci sınıf Jumeirah konumu, Meraas\'ın uzlaşmaz kalite standartları ve %6,8 beklenen getirinin birleşimi, Solaya\'yı dengeli yatırımcılar için cazip bir teklif yapıyor.',
    },
    highlights: {
      en: [
        'Prestigious Jumeirah beachfront neighbourhood',
        '6.8% projected yield in prime Meraas community',
        'Walking distance to La Mer and Jumeirah Beach',
        'Meraas master developer — City Walk, Bluewaters',
        'Effortless access to Sheikh Zayed Road',
        'Strong long-term capital appreciation in Jumeirah',
      ],
      tr: [
        'Prestijli Jumeirah sahil semti',
        'Birinci sınıf Meraas topluluğunda %6,8 beklenen getiri',
        'La Mer ve Jumeirah Plajı\'na yürüyüş mesafesi',
        'Meraas baş geliştirici — City Walk, Bluewaters',
        'Şeyh Zayed Yolu\'na zahmetsiz erişim',
        'Jumeirah\'da güçlü uzun vadeli sermaye değer artışı',
      ],
    },
    amenities: ['Beach Access', 'Infinity Pool', 'Spa & Yoga', 'Fine Dining', 'Private Garden', 'Valet Parking'],
  },
  {
    slug: 'one-river-point',
    name: 'One River Point',
    developer: 'Ellington',
    location: 'Business Bay, Dubai',
    fullAddress: 'Business Bay, Dubai, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$620,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    yield: '7.8%',
    completion: 'Q4 2027',
    beds: '1–3 Bed',
    floors: '42',
    totalUnits: '275',
    lat: 25.179,
    lng: 55.258,
    heroImage: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?q=80&w=1600',
    images: [
      'https://images.unsplash.com/photo-1486325212027-8081e485255e?q=80&w=900',
      'https://images.unsplash.com/photo-1628592102751-ba83b0314276?q=80&w=900',
      'https://images.unsplash.com/photo-1617098900591-3f90928e8c54?q=80&w=900',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=900',
    ],
    description: {
      en: "One River Point by Ellington Properties is a standout address in Business Bay, occupying a prized position directly on the Dubai Canal waterfront. This 42-storey tower offers one to three-bedroom apartments with spectacular unobstructed views along the canal towards Downtown Dubai, the Business Bay skyline and beyond.\n\nEllington's hallmark art-centric design philosophy is evident throughout One River Point: from curated art installations in the lobbies and common areas to carefully considered spatial planning within each residence. Business Bay's position as Dubai's fastest-growing submarket, combined with the development's canal frontage and Ellington's brand premium, drives consistent demand from high-quality tenants and international buyers.",
      tr: 'Ellington Properties\'ın One River Point projesi, doğrudan Dubai Kanalı sahil kesiminde değerli bir konuma sahip Business Bay\'de öne çıkan bir adrestir. 42 katlı bu kule, kanaldan Downtown Dubai, Business Bay silüetine ve ötesine uzanan muhteşem önünü açık manzaralarıyla bir ila üç yatak odalı daireler sunuyor.\n\nEllington\'ın damgasını vuran sanat merkezli tasarım felsefesi One River Point\'te kendini gösteriyor: lobi ve ortak alanlardaki küratörlüğünü üstlenilmiş sanat enstalasyonlarından her residencedeki özenle düşünülmüş mekân planlamasına kadar. Business Bay\'in Dubai\'nin en hızlı büyüyen alt pazarı olarak konumu, projenin kanal cephesiyle ve Ellington\'ın marka primiyle birleşerek yüksek kaliteli kiracılar ve uluslararası alıcılardan sürekli talep oluşturuyor.',
    },
    highlights: {
      en: [
        'Direct Dubai Canal waterfront position',
        '7.8% projected yield in Business Bay\'s hot submarket',
        'Ellington art-centric interiors and finishes',
        'Views to Burj Khalifa and Downtown Dubai',
        '42 floors of canal-facing residences',
        'Flexible payment plan with low deposit',
      ],
      tr: [
        'Doğrudan Dubai Kanalı sahil konumu',
        'Business Bay\'in sıcak alt pazarında %7,8 beklenen getiri',
        'Ellington sanat merkezli iç mekanlar ve bitiş malzemeleri',
        'Burj Khalifa ve Downtown Dubai manzarası',
        'Kanal cepheli 42 kat residence',
        'Düşük depozito ile esnek ödeme planı',
      ],
    },
    amenities: ['Canal Views', 'Infinity Pool', 'Art Gallery', 'Gym & Spa', 'Paddle Courts', 'Sky Deck'],
  },
  {
    slug: 'cala-del-mar',
    name: 'Cala Del Mar',
    developer: 'Ellington',
    location: 'Marjan Island, Ras Al Khaimah',
    fullAddress: 'Al Marjan Island, Ras Al Khaimah, United Arab Emirates',
    region: 'UAE',
    city: 'dubai',
    price: '$474,000',
    priceNote: { en: 'Starting from', tr: 'Başlangıç fiyatı' },
    yield: '9.0%',
    completion: 'Q2 2027',
    beds: '1–4 Bed',
    floors: '25',
    totalUnits: '292',
    lat: 25.6786,
    lng: 55.9428,
    heroImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1600',
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=900',
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=900',
      'https://images.unsplash.com/photo-1540541338537-09cf46717399?q=80&w=900',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=900',
    ],
    description: {
      en: "Cala Del Mar by Ellington Properties is one of the most anticipated waterfront developments in the UAE, set on the spectacular Al Marjan Island in Ras Al Khaimah — the region's fastest-growing emirate, soon to be home to the first integrated resort and casino in the Middle East.\n\nInspired by Mediterranean coastal living, Cala Del Mar offers generously proportioned one- to four-bedroom residences, each designed to maximise panoramic sea views through expansive floor-to-ceiling glazing and wide, sun-drenched terraces. Residents enjoy an exclusive private boardwalk, direct beach access and a comprehensive suite of resort-grade amenities, all within a community shaped by Ellington's signature attention to art, light and lived-in luxury.",
      tr: 'Ellington Properties\'ın Cala Del Mar projesi, Orta Doğu\'nun ilk entegre tatil köyüne ve kumarhanesine yakında ev sahipliği yapacak olan bölgenin en hızlı büyüyen emirliği Ras Al Khaimah\'daki muhteşem Al Marjan Adası\'nda konumlanan BAE\'deki en beklenen sahil projelerinden biridir.\n\nAkdeniz kıyı yaşamından ilham alan Cala Del Mar, geniş zemin kat tavana cam ve geniş güneşli teraslar aracılığıyla panoramik deniz manzarasını maksimize edecek şekilde tasarlanmış, geniş hacimli bir ila dört yatak odalı residence\'lar sunuyor. Sakinler, Ellington\'ın sanat, ışık ve yaşanmış lükse özgü ilgisiyle şekillendirilen bir topluluk içindeki özel bir boardwalk, doğrudan plaj erişimi ve kapsamlı tatil niteliğinde olanaklar paketinin keyfini çıkarıyor.',
    },
    highlights: {
      en: [
        'Al Marjan Island — UAE\'s most exciting new destination',
        '9.0% projected yield alongside Wynn Resort (opening 2027)',
        'Mediterranean-inspired beachfront living',
        'Direct sea access and private boardwalk',
        'Ellington\'s signature art and light-filled design',
        'Entry from $474,000 — strong appreciation outlook',
      ],
      tr: [
        'Al Marjan Adası — BAE\'nin en heyecan verici yeni destinasyonu',
        'Yeni açılacak Wynn Resort (2027) yakınında %9,0 beklenen getiri',
        'Akdeniz ilhamlı sahil yaşamı',
        'Doğrudan deniz erişimi ve özel boardwalk',
        'Ellington\'ın imzalı sanat ve ışık dolu tasarımı',
        '474.000$\'dan giriş — güçlü değer artışı beklentisi',
      ],
    },
    amenities: ['Private Beach', 'Boardwalk', 'Infinity Pool', 'Yoga Pavilion', 'Kids Waterpark', 'Beachfront Dining'],
  },
];

export function getPropertyBySlug(slug: string): PropertyData | undefined {
  return allProperties.find((p) => p.slug === slug);
}

export function getPropertiesByCity(city: 'london' | 'dubai'): PropertyData[] {
  return allProperties.filter((p) => p.city === city);
}
